" Vim syntax file for telic (.telic)
" GENERATED by tools/gen-editors.py from docs/reference.md — do not edit by hand.
" Relies on the broad 'iskeyword' set below so punctuation words (+, ~, >r,
" @i,j, has?, kebab-case) match as keywords.

if exists("b:current_syntax")
  finish
endif

syn case match
syn iskeyword @,48-57,_,192-255,33,35-39,42-47,58,60-64,94,126

syn sync fromstart

syn match   telicComment "\%(^\|\s\)\zs\\\%(\s.*\)\=$" contains=@Spell
syn region  telicComment start="\[\@<!(\s" end=")" contains=@Spell
syn region  telicString start=+"+ skip=+""+ end=+"+ contains=@Spell,telicFormat
syn match   telicFormat "{\d\+\%(:[^}]*\)\=}" contained
syn match   telicNumber "\<-\=\d\+\%(\.\d\+\)\=\%([eE][-+]\=\d\+\)\=\>"
syn match   telicSymbol  ":\k\+"
syn match   telicPath    "/\a\k*"
syn match   telicFrameOp  "[@!]\ze\k"
syn match   telicFrameKey "[@!]\@<=\k\+"

syn keyword telicDefine : variable constant symbol to forget inline internal ' lookup
syn match   telicDefine ";"
syn match   telicDefine "\[:"
syn match   telicDefine ":\]"
syn match   telicDefName "\%(^\|\s\):\s\+\zs\k\+"

syn keyword telicConditional if ?if else then
syn keyword telicRepeat begin until again while repeat leave continue times i-times
syn keyword telicKeyword exit execute

syn keyword telicLogic lvar unify ~ deref $ amb fail _
syn keyword telicBoolean null

syn match   telicDelimiter "[][{}]"
syn match   telicDelimiter "\%(^\|\s\)\zs[<>]\ze\%(\s\|$\)"
syn match   telicDelimiter "\[<"
syn match   telicDelimiter ">\]"
syn match   telicDelimiter "\%(^\|\s\)\zs|\ze\%(\s\|$\)"

syn keyword telicBuiltin +! -! *! /! ++ -- f++ f-- f1+ f1- f+ f-
syn keyword telicBuiltin f* f/ f^ 1+ 1- 0= + - * / % ^
syn keyword telicBuiltin = <= >= f= f< f> f<= f>= !i ! @i,j @i
syn keyword telicBuiltin @j @ >r >side side> 2dup .s .a . !e !i,j ,
syn keyword telicBuiltin -rot 0-matrix 1= 2curry 2drop ? @e @or C E G H
syn keyword telicBuiltin HBAR KB NA PHI PI QE TAU abs acos add-last! after-entry aggregate
syn keyword telicBuiltin all? alloc-stats and any? append-file apropos arg argmax argmin args argsort array
syn keyword telicBuiltin array-of array>frame array>set array? as as-column asin assoc atan atan2 auc augment
syn keyword telicBuiltin base basename between? binary-dir binomial-deviance bit-and bit-not bit-or bit-xor bootstrap bootstrap-with brier
syn keyword telicBuiltin bye byte-size byte-substring bytes>value callers case cat catch cd char-at choose ci
syn keyword telicBuiltin clamp clear close codepoint-at codepoint>char codepoints>string column-maxes column-means column-mins column-sums column-type column>array
syn keyword telicBuiltin column>set complete-cases complete-rows complex complex? concat conjugate continuation? copy copy-file cor correlate-with
syn keyword telicBuiltin correlation-kendall correlation-pearson correlation-spearman cos cosh count covariance cp cr cross-validate cumulative-sum curry
syn keyword telicBuiltin cv-folds cwd dataset>matrix dataset>rows date-shift date>epoch date>epoch-local days-in-month db-close db-exec db-open db-query
syn keyword telicBuiltin db? defer delete-at delete-directory delete-file denominator depth diagonal diagonal-matrix difference dim do
syn keyword telicBuiltin dot drop drop-nans dup each ecdf edit edit-distance embodies embodies! emit end-process
syn keyword telicBuiltin endcase endof ensure env env! epoch>date epoch>date-local eq erf erfc evaluate exact>float
syn keyword telicBuiltin exact? exp expand-grid expect expect-near expect-throws expect= f*+ f*- fabs facos false
syn keyword telicBuiltin false? fasin fatan fcos fexp ffi-free ffi-function ffi-open ffi-variadic file-exists? file-info filter
syn keyword telicBuiltin filter-columns find-executable find-first first flat-map flatten flatten-array fln fln1+ float>exact float? floats>matrix
syn keyword telicBuiltin flog fmod fnegate fold-times format format-time format-time-local frame frame>array frame>json frame? frames>dataset
syn keyword telicBuiltin frobenius-norm fround fround-down fround-up fsin fsq fsqrt ftan ftanh ftruncate gauges gauges>rows
syn keyword telicBuiltin gc gen-each gen-take group-by group-indices group-with halt has? head headn help histogram-table
syn keyword telicBuiltin hstack identity identity-matrix imaginary-part in? index-of int-segment intersection iota iqr iso>time join
syn keyword telicBuiltin json>frame key-set keys ks-distance last lgamma list-directory ln ln1+ load load-library load-tsv
syn keyword telicBuiltin load-value log log10 log2 loop lower-case lowest-bit ls lshift lvar? magnitude make-directory
syn keyword telicBuiltin man map match match-all matches? matmul matrix matrix-range matrix>array matrix>pointer matrix? max
syn keyword telicBuiltin max2 mean median merge merge-by mesh min min2 mkdir mod mv n-columns
syn keyword telicBuiltin n-rows name!key name@key nan? ncurry negate neq new-tests nip nlast nmap nonmissing-count
syn keyword telicBuiltin norm not now null? num-cores num-elements numerator of on-tick open-app-window open-file or
syn keyword telicBuiltin over pad-left pad-right parallel-run parse-time partition pbootstrap peek percentile pfilter pfilter-ext pick
syn keyword telicBuiltin pmap pmap-ext pmap-reduce pmap-reduce-ext pnorm pointer-cell pointer-deref pointer-long pointer-string-at pointer>address print print-gauges
syn keyword telicBuiltin print-stack product-times ptr? pwd qnorm quantile quantiles quantity? query query-rows quotient r>
syn keyword telicBuiltin r@ random random-int random-normal range ranks rationalize read read-available read-err read-file read-line
syn keyword telicBuiltin read-out read-tsv real-part recurse reduce reify reload remove-last! rename-file rename-key! render repeat-column!
syn keyword telicBuiltin replace replace-where! resample resample-indices resample-indices-ext reset reshape rest resume reverse rm rmdir
syn keyword telicBuiltin roll rot round round-down round-up row-at row-maxes row-means row-mins row-sums rows>dataset rshift
syn keyword telicBuiltin run run-result running? sample sample-with-replacement sample-without-replacement save save-tsv save-value se second see
syn keyword telicBuiltin see-compiled see-compiled>string see-tree see-tree>string see>string seed segment>pointer segment? select-columns select-eq select-keys select-neq
syn keyword telicBuiltin select-rows select-values set set-add! set-remove! set-unit! set>array set? shift shift-with shuffle side-depth
syn keyword telicBuiltin side-drop side-peek sigmoid sin sinh size skip sleep slice! solutions sort sort-by
syn keyword telicBuiltin sort-rows sort-rows-descending spaces split split-by spread sq sqrt start-generator start-process std stderr
syn keyword telicBuiltin stdin stdout stdout>string stop stream? string>chars string>codepoints string>number string>symbol string? submatrix substring
syn keyword telicBuiltin successive-differences sum sum-times summary swap symbol? take take-solutions tan tanh telic telic-version
syn keyword telicBuiltin test test-report throw tick-every time>iso timed to-slice! touch touch-file trace transpose trim
syn keyword telicBuiltin true true? truncate try-catch tsv>db tty? tuck type-of unify? union unit unit-of
syn keyword telicBuiltin update-at upper-case value>bytes values var variables vars vector vf* vf+ vf- vf/
syn keyword telicBuiltin vfabs vfcos vfexp vflog vfneg vfsin vfsq vfsqrt vftan vftanh vstack vvf*
syn keyword telicBuiltin vvf*+ vvf*- vvf+ vvf- vvf/ wait wait-readable wall-now where wildcard? with-db with-stream
syn keyword telicBuiltin within-groups words write write-file write-in write-tsv xml-escape xt? yield zero-variance?

hi def link telicComment      Comment
hi def link telicString       String
hi def link telicNumber       Number
hi def link telicSymbol       Constant
hi def link telicPath         Constant
hi def link telicFrameOp      Operator
hi def link telicFrameKey     Type
hi def link telicDefine       Define
hi def link telicDefName      Function
hi def link telicConditional  Conditional
hi def link telicRepeat       Repeat
hi def link telicKeyword      Keyword
hi def link telicLogic        Special
hi def link telicBoolean      Boolean
hi def link telicDelimiter    Delimiter
hi def link telicBuiltin      Statement
hi def link telicFormat       SpecialChar

let b:current_syntax = "telic"
