/* Generated from docs/reference.md by tools/gen-help.py.
   Do not edit by hand; rerun the generator instead. */

#include "logicforth.h"

const HelpEntry help_entries[] = {
	{ "!", "( fr sym/path val -- fr )", "Set by key or path, vivifying intermediates; mutates fr; errors on a search path", "d log n", "realloc on growth; 1o per vivified frame", "O(d log n) amortized" },
	{ "!i", "( arr i val -- arr )", "Store val at index i in place; leaves arr on the stack", "4", "none", "O(1)" },
	{ "$", "( v -- val )", "lib.l4: deref (inlined)", "d", "none", "O(d)" },
	{ "%", "( a b -- remainder quotient )", "floats only; truncating division: pushes a − trunc(a/b)·b then trunc(a/b); errors on zero", "4", "none", "O(1)" },
	{ "'", "( \"name\" -- xt )", "Parse the following word at compile time and push its xt (immediate; folds the xt in as a literal)", NULL, NULL, NULL },
	{ "*", "( a b -- a*b )", "float: multiply. set∩set: intersection. matrix: element-wise. scalar/matrix broadcast.", "3 (float)", "as +", "as +" },
	{ "*!", "( m a -- m )", "in-place multiply", "3 + r×c", "none", "O(r×c)" },
	{ "+", "( a b -- a+b )", "float: add. string+string: concat → new string. set+set: union → new set. matrix+matrix: element-wise → new matrix. scalar+matrix / matrix+scalar: broadcast → new matrix. array+array: defers to concat.", "3 (float)", "float none; string 1s + temp buffer; set 1o; matrix 1m(r×c); array 1a(m+n)", "float O(1); string O(|s|); set O(n log n); matrix O(r×c); array O(m+n)" },
	{ "+!", "( m a -- m )", "matrix+matrix or matrix+scalar (and scalar+matrix, mutating the matrix) in place", "3 + r×c", "none", "O(r×c)" },
	{ "++", "( -- )", "Increment the named local by 1 in place", "1", "none", "O(1)" },
	{ "-", "( a b -- a-b )", "float: subtract. set−set: difference. matrix: element-wise. scalar/matrix broadcast.", "3 (float)", "as +", "as +" },
	{ "-!", "( m a -- m )", "in-place subtract", "3 + r×c", "none", "O(r×c)" },
	{ "--", "( -- )", "Decrement the named local by 1 in place", "1", "none", "O(1)" },
	{ ".", "( a -- )", "Print value then a space; matrices print as a grid, frames pretty-print", "1 + print", "none", "O(size printed)" },
	{ ".a", "( a -- )", "Like . but disables print truncation (show all elements)", "1 + print", "none", "O(size printed)" },
	{ ".s", "( -- )", "Print every stack value, bottom to top; leaves the stack intact", "print", "none", "O(depth)" },
	{ "/", "( a b -- a/b )", "float: divide (errors on zero divisor). matrix÷matrix: element-wise (errors on any zero element). scalar/matrix broadcast.", "3 (float)", "matrix 1m(r×c)", "float O(1); matrix O(r×c)" },
	{ "/!", "( m a -- m )", "in-place divide", "3 + r×c", "none", "O(r×c)" },
	{ "0-matrix", "( r c -- m )", "r×c zero matrix (calloc)", "3", "1m(r×c)", "O(1)+" },
	{ "0=", "( a -- bool )", "!truthy(a); any type", "2", "none", "O(1)" },
	{ "1+", "( a -- a+1 )", "float or matrix", "2 (float)", "matrix 1m(r×c)", "float O(1); matrix O(r×c)" },
	{ "1-", "( a -- a-1 )", "float or matrix", "2 (float)", "matrix 1m(r×c)", "float O(1); matrix O(r×c)" },
	{ "2drop", "( a b -- )", "lib.l4: drop drop (inlined)", "6", "none", "O(1)" },
	{ "2dup", "( a b -- a b a b )", "lib.l4: over over (inlined)", "10", "none", "O(1)" },
	{ ":", "—", "Begin a colon definition; read the following name; enter compile mode", NULL, NULL, NULL },
	{ ":name", "( -- sym )", "Symbol literal; interns the name at read time", NULL, NULL, NULL },
	{ ";", "—", "End a colon definition; emit exit; store the source text for see", NULL, NULL, NULL },
	{ "=", "( a b -- bool )", "structural equality", "3 (float)", "none", "float O(1); string O(|s|); array/set O(n); frame O(n); matrix O(r×c)" },
	{ ">r", "( a -- ) → return stack", "Move top to return stack", "2", "none", "O(1)" },
	{ ">side", "( a -- )", "Push to side stack", "2", "none", "O(1)" },
	{ "?if", "( flag -- flag )", "Like if, but peeks the flag instead of consuming it — the flag stays on the stack in both branches", NULL, NULL, NULL },
	{ "@", "( fr sym/path -- val )", "Get by key or path; errors if absent or if the path is a search path", "3 + d log n", "none", "O(d log n)" },
	{ "@i", "( arr i -- val )", "Array element; on a matrix returns row i as a 1×c matrix", "3 (array)", "matrix 1m(1×c)", "O(1) array; O(c) matrix" },
	{ "@i,j", "( m i j -- f )", "Single element as a float", "4", "none", "O(1)" },
	{ "@j", "( m j -- col )", "Column j as an r×1 matrix (copy)", "2 + r", "1m(r×1)", "O(r)" },
	{ "[:", "( -- xt )", "Open an anonymous quotation (closed by :]); compiles its body and pushes its xt", NULL, NULL, NULL },
	{ "^", "( a b -- a^b )", "pow; float or matrix (element-wise) / scalar broadcast", "3 (float)", "matrix 1m(r×c)", "float O(1); matrix O(r×c)" },
	{ "_", "( -- wild )", "The anonymous wildcard — unifies with anything, binds nothing, allocates nothing (a constant, not a fresh var)", "2", "none", "O(1)" },
	{ "abs", "( a -- |a| )", "fabs", "2 (float)", "matrix 1m(r×c)", "float O(1); matrix O(r×c)" },
	{ "acos", "( a -- acos a )", "inverse cosine", "2", "matrix 1m(r×c)", "same" },
	{ "again", "—", "Unconditional branch back to begin", NULL, NULL, NULL },
	{ "alloc-stats", "( -- )", "Print and reset the allocation counters since the last call (lvars=… arrays=…)", "2", "none", "O(1)" },
	{ "amb", "( xt1 xt2 -- … )", "Run xt1; if it fails (a unify mismatch or fail), roll its bindings back through the trail and run xt2. Commits to the first branch that succeeds.", "xt1", "none", "O(xt1 + xt2)" },
	{ "and", "( a b -- bool )", "logical and of truthiness", "3", "none", "O(1)" },
	{ "append-file", "( s path -- )", "Open in append mode, write the string's bytes", "file write", "none", "O(|s|)" },
	{ "array", "( v₀ … vₙ₋₁ n -- arr )", "Gather the top n values into an array", "2 + n", "1a(n)", "O(n)" },
	{ "array-of", "( val n -- arr )", "New n-element array, every slot = val", "3 + n", "1a(n)", "O(n)" },
	{ "array>cons", "( arr -- list )", "Cons chain from an array's elements (last element becomes the tail; [ ] → null)", "n", "n−1 pairs", "O(n)" },
	{ "array>frame", "( arr -- fr )", "Build from an even-length alternating-kv array; a path key (/a/b/c) vivifies nested frames", "1 + n log n", "1o + reallocs", "O(n log n)" },
	{ "array>set", "( array -- set )", "Sort a copy of the array once and dedup into a set — the fast bulk constructor (one sort, not n inserts); the source array is unchanged", "n log n", "1o + realloc", "O(n log n)" },
	{ "asin", "( a -- asin a )", "inverse sine", "2", "matrix 1m(r×c)", "same" },
	{ "assert", "( rel row -- rel )", "Add row to :rows and to each indexed column's bucket; identical row is a no-op. Mutates rel in place, returns it", "k + n", "reallocs", "O(n)" },
	{ "atan", "( a -- atan a )", "inverse tangent", "2", "matrix 1m(r×c)", "same" },
	{ "begin", "—", "Mark a loop top", NULL, NULL, NULL },
	{ "bulk-load", "( rel rows-array -- rel )", "Load all rows at once: builds :rows (a deduped set) and each declared column's index, instead of row-by-row", "—", "sets + frame", "O(n log n)" },
	{ "bye", "( -- )", "exit(0)", "—", "—", "—" },
	{ "catch", "( xt -- result 0 | exc 1 )", "lib.l4: reset execute 0", "—", "cont if thrown", "O(xt)" },
	{ "choose", "( list cont -- )", "lib.l4: run cont with each element of a cons list in turn, committing to the first for which it succeeds; fail if none do (n-way amb over a list)", "n·cont", "none", "O(n·cont)" },
	{ "clear", "( … -- )", "Reset data stack depth to 0", "1", "none", "O(1)" },
	{ "close", "( stream -- )", "Close the fd; closing a child's :in sends it EOF", "1 syscall", "none", "O(1)" },
	{ "column-maxes", "( m -- m' )", "1×c of per-column maxima", "1 + r×c", "1m(1×c)", "O(r×c)" },
	{ "column-means", "( m -- m' )", "lib.l4: column-sums then scalar ÷", "r×c", "2×1m(1×c)", "O(r×c)" },
	{ "column-mins", "( m -- m' )", "1×c of per-column minima", "1 + r×c", "1m(1×c)", "O(r×c)" },
	{ "column-sums", "( m -- m' )", "1×c of per-column sums", "1 + r×c", "1m(1×c)", "O(r×c)" },
	{ "concat", "( arr/set arr/set -- arr )", "Concatenated copy", "2 + m + n", "1a(m+n)", "O(m+n)" },
	{ "cons", "( head tail -- pair )", "Build a cons cell", "2", "1 pair", "O(1)" },
	{ "cons>array", "( list -- arr )", "Walk a cons chain into an array, **dereferencing** the spine and each element and including the terminal (works on relational results)", "n", "1a(n)", "O(n)" },
	{ "copy", "( a -- a' )", "Deep copy of any value, copy_term-style: dereferences bound logic vars to their values and gives each unbound var a fresh shared var; recurses into frames, arrays, matrices, strings, sets, continuations, pairs; identity for scalars. Defined generally, not frame-specific.", "tree size", "one object per node", "O(tree size)" },
	{ "cos", "( a -- cos a )", "cosine (radians)", "2", "matrix 1m(r×c)", "same" },
	{ "count-matches", "( rel pattern -- n )", "How many rows match; for a covering query this is the bucket's size with no scan, otherwise query size", "—", "(covering: none)", "O(candidates)" },
	{ "cr", "( -- )", "Print a newline", "1", "none", "O(1)" },
	{ "create-index", "( rel cols -- rel )", "Index a relation on the symbol columns cols: intern each indexed column's value to a symbol (so it keys the bucket and matches a { :col :val } pattern), then load-bag into a cols-indexed relation. Other columns keep their type; :rows stays a bag. The explicit bridge from a db-query result to an indexed relation", "n", "frame + sets", "O(n)" },
	{ "db-close", "( db -- )", "Close the connection and free its registry slot. Idempotent — closing an already-closed handle is a no-op. A handle that is dropped without closing leaks the connection until process exit", "1 syscall", "none", "O(1)" },
	{ "db-exec", "( db statement params -- n )", "Bind params to the statement's ? placeholders and run it with no result set (INSERT / UPDATE / DELETE / CREATE / …); return the affected-row count as a float (0 for DDL). One statement per call. On a bad statement, errors with SQLite's message", "per statement", "none", "O(statement)" },
	{ "db-open", "( path -- db )", "Open (creating if absent) the database file at path and push a handle; \":memory:\" is a private in-memory database. Errors if it can't be opened", "open", "1 connection (not GC'd)", "O(1)+" },
	{ "db-query", "( db query params -- rel )", "Bind params to the query's ? placeholders and run it; return an index-less relation { :rows <array of row frames> :index { } }. Each row is a frame keyed by column-name symbols, with INTEGER/REAL → float, TEXT → string, NULL → null, BLOB → string of raw bytes. :rows is a **bag** — duplicates kept, in result order. On a bad query, errors with SQLite's message", "n·c", "1o relation + 1a(n) + 1o/row + a string per text/blob cell", "O(n·c)" },
	{ "delete-at", "( fr sym/path -- fr )", "Remove a key (errors if absent or on a search path); mutates fr", "n", "none", "O(n)" },
	{ "depth", "( -- n )", "Push current depth", "1", "none", "O(1)" },
	{ "deref", "( v -- val )", "Follow a logic var's binding chain to the first non-variable value (v itself if unbound). Shallow — a returned structure still has bound vars inside; for a fully resolved snapshot use reify or copy", "d", "none", "O(d)" },
	{ "destruct", "( arr/set/fr -- v… )", "Spread elements onto the stack; a frame spreads alternating sym/value", "1 + n", "none", "O(n)" },
	{ "destruct-to", "( source targets -- )", "source and target arrays; assign each source element to the variable named by the corresponding target (symbol or xt), creating it if needed", "2 + n", "may create variables", "O(n)" },
	{ "dgemm-nn", "( α A B β C -- R )", "R = α·A·B + β·C, ikj fast path", "5 + m·k·n", "1m(m×n)", "O(m·k·n)" },
	{ "dgemm-nt", "( α A B β C -- R )", "R = α·A·Bᵀ + β·C", "5 + m·k·n", "1m(m×n)", "O(m·k·n)" },
	{ "dgemm-tn", "( α A B β C -- R )", "R = α·Aᵀ·B + β·C", "5 + m·k·n", "1m(m×n)", "O(m·k·n)" },
	{ "dgemm-tt", "( α A B β C -- R )", "R = α·Aᵀ·Bᵀ + β·C", "5 + m·k·n", "1m(m×n)", "O(m·k·n)" },
	{ "diagonal", "( m -- m' )", "Diagonal as a 1×min(r,c) matrix", "1 + min(r,c)", "1m(1×min)", "O(min(r,c))" },
	{ "diagonal-matrix", "( fill n -- m )", "n×n matrix with fill on the diagonal", "2 + n", "1m(n×n)", "O(n)" },
	{ "difference", "( s₁ s₂ -- s₃ )", "s₁ − s₂ into a new set, merging the two sorted arrays", "m+n", "1o + reallocs", "O(m+n)" },
	{ "dim", "( m -- r c )", "Push rows then columns", "3", "none", "O(1)" },
	{ "drop", "( a -- )", "Discard top", "1", "none", "O(1)" },
	{ "dup", "( a -- a a )", "Duplicate top", "3", "none", "O(1)" },
	{ "else", "—", "Separate the true and false arms", NULL, NULL, NULL },
	{ "emit", "( n -- )", "Print the character with codepoint n", "1", "none", "O(1)" },
	{ "env", "( name -- val )", "Environment variable as a string, or the none value if unset (so set-empty \"\" and unset stay distinct)", "1", "1o on hit", "O(|val|)" },
	{ "env!", "( name value -- )", "Set an environment variable (overwriting); process-wide, so subsequent start-process children inherit it", "1", "none", "O(1)" },
	{ "execute", "( xt -- … )", "Call the word at xt", NULL, NULL, NULL },
	{ "exit", "( -- )", "Return early from the current definition (this one runs at run time)", NULL, NULL, NULL },
	{ "exp", "( a -- eᵃ )", "exp", "2", "matrix 1m(r×c)", "same" },
	{ "f*", "( a b -- a*b ) ⚠", "multiply", "2", "none", "O(1)" },
	{ "f*+", "( a b c -- a*b+c ) ⚠", "fused multiply-add; result in slot of a", "3", "none", "O(1)" },
	{ "f*-", "( a b c -- c-a*b ) ⚠", "fused multiply-subtract", "3", "none", "O(1)" },
	{ "f+", "( a b -- a+b ) ⚠", "add, result in deeper slot", "2", "none", "O(1)" },
	{ "f++", "( -- ) ⚠", "Unsafe float increment: raw .number mutation, no tag check, for a local known to hold a float", "1", "none", "O(1)" },
	{ "f-", "( a b -- a-b ) ⚠", "subtract", "2", "none", "O(1)" },
	{ "f--", "( -- ) ⚠", "Unsafe float decrement: raw .number mutation, no tag check", "1", "none", "O(1)" },
	{ "f/", "( a b -- a/b ) ⚠", "divide; checks divisor ≠ 0", "2", "none", "O(1)" },
	{ "f1+", "( a -- a+1 ) ⚠", "in place", "1", "none", "O(1)" },
	{ "f1-", "( a -- a-1 ) ⚠", "in place", "1", "none", "O(1)" },
	{ "f^", "( a b -- a^b ) ⚠", "pow", "2", "none", "O(1)" },
	{ "fabs", "( a -- |a| ) ⚠", "in place", "1", "none", "O(1)" },
	{ "facos", "( a -- acos a ) ⚠", "inverse cosine, in place", "1", "none", "O(1)" },
	{ "fail", "( -- )", "Backtrack to the nearest enclosing amb, failing the current branch; with no enclosing amb, an error", "1", "none", "O(L)" },
	{ "fasin", "( a -- asin a ) ⚠", "inverse sine, in place", "1", "none", "O(1)" },
	{ "fatan", "( a -- atan a ) ⚠", "inverse tangent, in place", "1", "none", "O(1)" },
	{ "fcos", "( a -- cos a ) ⚠", "cosine (radians), in place", "1", "none", "O(1)" },
	{ "fexp", "( a -- eᵃ ) ⚠", "in place", "1", "none", "O(1)" },
	{ "filter", "( arr/set xt -- arr )", "Keep elements where xt is truthy", "2 + n·xt", "malloc(n) flags + 1a(k)", "O(n·xt)" },
	{ "flatten", "( m -- m' )", "lib.l4: 1×(r·c) reshape", "r×c", "1m(1×r·c)", "O(r×c)" },
	{ "fln", "( a -- ln a ) ⚠", "natural log, in place", "1", "none", "O(1)" },
	{ "flog", "( a -- log₁₀ a ) ⚠", "base-10 log, in place", "1", "none", "O(1)" },
	{ "fmod", "( a b -- fmod(a,b) ) ⚠", "fmod", "2", "none", "O(1)" },
	{ "fnegate", "( a -- -a ) ⚠", "in place", "1", "none", "O(1)" },
	{ "forget", "—", "Read the following name; truncate the dictionary back to before it", NULL, NULL, NULL },
	{ "format", "( … template -- s )", "Fill template's {n} placeholders with the nth-from-top stack value, then drop exactly the referenced positions (unreferenced values stay); renders floats/strings/symbols. Only {digits} substitute — other brace content is left literal", "len + refs", "1o", "O(len)" },
	{ "frame", "( keys values -- fr )", "Build from parallel key and value arrays of equal length", "2 + n log n", "1o + reallocs", "O(n log n)" },
	{ "frame>array", "( fr -- arr )", "Flatten to a key-sorted alternating-kv array; inverse of array>frame", "1 + n", "1o", "O(n)" },
	{ "frame>json", "( val -- s )", "Serialize a value to JSON. Floats use the shortest round-trip form; strings are escaped (non-ASCII emitted raw); object keys are the symbol names", "walk + build", "1o string", "O(tree size)" },
	{ "fround", "( a -- round a ) ⚠", "nearest, in place", "1", "none", "O(1)" },
	{ "fround-down", "( a -- floor a ) ⚠", "in place", "1", "none", "O(1)" },
	{ "fround-up", "( a -- ceil a ) ⚠", "in place", "1", "none", "O(1)" },
	{ "fsin", "( a -- sin a ) ⚠", "sine (radians), in place", "1", "none", "O(1)" },
	{ "fsq", "( a -- a² ) ⚠", "in place", "1", "none", "O(1)" },
	{ "fsqrt", "( a -- √a ) ⚠", "in place", "1", "none", "O(1)" },
	{ "ftan", "( a -- tan a ) ⚠", "tangent (radians), in place", "1", "none", "O(1)" },
	{ "ftanh", "( a -- tanh a ) ⚠", "hyperbolic tangent, in place", "1", "none", "O(1)" },
	{ "ftruncate", "( a -- trunc a ) ⚠", "toward zero, in place", "1", "none", "O(1)" },
	{ "gc", "( -- )", "Force a mark-sweep now", "walks stacks + dict + roots, frees unmarked", "none", "O(objects + dict)" },
	{ "gen-each", "( producer consumer -- )", "lib.l4: run consumer on each value the producer yields until the producer falls off (a :gen-end sentinel marks exhaustion)", "—", "cont/step", "O(values · consumer)" },
	{ "gen-take", "( producer count -- array )", "lib.l4: the first count values the producer yields, collected into an array", "—", "1a(count) + cont/step", "O(count · L)" },
	{ "group-by", "( array col -- frame )", "Group an array of frames by their symbol-valued col into a frame from each value to a set of the matching rows; one sorted pass, distinct values sorted", "n log n", "frame + sets", "O(n log n)" },
	{ "gt", "( a b -- bool )", "greater-than", "3 (float)", "none", "same" },
	{ "has?", "( fr sym/path -- bool )", "Existence test for a frame key or path, no error on miss; a search path is true if any node matches (short-circuits at the first); on a string ( s pat -- bool ), true if regex pat matches anywhere", "3 + d log n", "none", "O(d log n)" },
	{ "head-tail", "( pair -- head tail )", "Split a pair — head under, tail on top; no auto-deref; errors on a non-pair", "1", "none", "O(1)" },
	{ "help", "( \"name\" -- )", "lib.l4: parse the next word and print its man frame (lookup man .)", "dict scan + log n", "1o + strings + print", "O(|dict|)" },
	{ "i-times", "( xt n -- )", "Run xt n times, pushing index 0..n-1 first", "2 + n·(1+xt)", "none", "O(n·xt)" },
	{ "identity-matrix", "( n -- m )", "lib.l4: 1 swap diagonal-matrix", "n", "1m(n×n)", "O(n)" },
	{ "if", "( flag -- )", "Branch past the then/else if flag is falsy", NULL, NULL, NULL },
	{ "inline", "—", "Mark the most recent definition inline; future calls splice its body", NULL, NULL, NULL },
	{ "inner-join", "( driver probed col -- [rows] )", "Inner join: each driver row merged (probed columns win collisions) with each probed row sharing col's value; probed must index col", "—", "1a", "O(driver·log probed)" },
	{ "intersection", "( s₁ s₂ -- s₃ )", "Intersection into a new set, merging the two sorted arrays", "m+n", "1o + reallocs", "O(m+n)" },
	{ "join", "( arr sep -- s )", "Concatenate the string elements of arr separated by sep; errors on a non-string element", "2 + total", "1o", "O(total)" },
	{ "json>frame", "( s -- val )", "Parse a JSON string. Escapes and \\uXXXX (with surrogate pairs) decode to UTF-8; recursive-descent, depth-guarded; rejects trailing non-whitespace", "scan + build", "one object per node", "O(|s|)" },
	{ "keys", "( fr -- arr )", "Keys (symbols) in sorted order", "1 + n", "1a(n)", "O(n)" },
	{ "last", "( arr n -- arr )", "lib.l4: swap reverse swap take reverse", "3n", "3×1a(n)", "O(n)" },
	{ "ln", "( a -- ln a )", "log — natural log", "2", "matrix 1m(r×c)", "same" },
	{ "load", "( s -- )", "Run a source file as if typed; record it for reload", "file read + run", "input buffer", "O(file)" },
	{ "load-bag", "( rel rows-array -- rel )", "Like bulk-load, but :rows stays a **bag** (the array, duplicates kept) rather than a deduped set; only :index is built", "n", "frame + sets", "O(n)" },
	{ "load-image", "( s -- )", "Restore a binary snapshot, replacing current state", "deserialize all", "reallocates all objects", "O(objects)" },
	{ "log", "( a -- log₁₀ a )", "log10", "2", "matrix 1m(r×c)", "same" },
	{ "lookup", "( \"name\" -- xt )", "Parse the following word at run time and push its xt — the non-immediate counterpart of '", NULL, NULL, NULL },
	{ "lt", "( a b -- bool )", "less-than", "3 (float)", "none", "same" },
	{ "lvar", "( -- v )", "Push a fresh, unbound logic variable", "2", "1 lvar", "O(1)" },
	{ "man", "( xt -- fr )", "Frame of a word's reference entry (:word :effect :summary, plus :ops :alloc :order for runtime words); T_NONE if undocumented", "dict scan + log n", "1o + strings", "O(|dict|)" },
	{ "map", "( arr/set xt -- arr )", "Apply xt to each element; xt must net exactly one value", "2 + n·xt", "1a(n)", "O(n·xt)" },
	{ "mapn", "( arr₁ … arr_N xt N -- arr )", "N-ary zip-map over equal-length arrays", "rows·(N+xt)", "1a(rows)", "O(rows·xt)" },
	{ "match", "( s pat -- [ whole cap… ] | 0 )", "First (leftmost) match as a flat array: whole match then each capture; no match returns 0", "n", "1a + captures", "O(n)" },
	{ "match-all", "( s pat -- [ [whole cap…] … ] | 0 )", "Every non-overlapping leftmost match, each a flat sub-array; a zero-width match advances one byte; no match returns 0", "n", "1a per match + captures", "O(n + m·g)" },
	{ "matches?", "( a b -- flag )", "Non-destructive unify test: mark the trail, unify a and b, roll the trail back, push whether they unified. Leaves no bindings and never backtracks (so it composes in straight-line code, unlike unify)", "n", "none", "O(n)" },
	{ "matrix", "( arr r c -- m ) or ( arr r -- m )", "Build from a float array; two-arg form takes r = rows and infers columns", "3 + r×c", "1m(r×c)", "O(r×c)" },
	{ "matrix-range", "( start end step -- m )", "1×N row of evenly spaced values", "3 + N", "1m(1×N)", "O(N)" },
	{ "max", "( m -- f )", "Maximum element", "1 + r×c", "none", "O(r×c)" },
	{ "mean", "( m -- f )", "lib.l4: sum ÷ element count", "r×c", "none", "O(r×c)" },
	{ "member?", "( set v -- bool )", "Binary-search membership", "3 + log n", "none", "O(log n)" },
	{ "merge", "( fr₁ fr₂ -- fr )", "New frame with all keys; fr₂ wins collisions", "(m+n) log(m+n)", "1o + reallocs", "O((m+n) log(m+n))" },
	{ "min", "( m -- f )", "Minimum element", "1 + r×c", "none", "O(r×c)" },
	{ "mod", "( a b -- remainder )", "lib.l4: % drop; sign follows dividend", "5", "none", "O(1)" },
	{ "negate", "( a -- -a )", "float or matrix (element-wise)", "2 (float)", "matrix 1m(r×c)", "float O(1); matrix O(r×c)" },
	{ "nip", "( a b -- b )", "lib.l4: swap drop (inlined)", "5", "none", "O(1)" },
	{ "not", "( a -- bool )", "logical not of truthiness", "2", "none", "O(1)" },
	{ "now", "( -- f )", "CLOCK_MONOTONIC seconds as a float", "1", "none", "O(1)" },
	{ "null", "( -- none )", "Push the none value (T_NONE) — what JSON null parses to, and what an unset env returns", "1", "none", "O(1)" },
	{ "num-cores", "( -- n )", "Online CPU count (sysconf)", "1", "none", "O(1)" },
	{ "num-elements", "( m -- n )", "lib.l4: dim *", "5", "none", "O(1)" },
	{ "or", "( a b -- bool )", "logical or of truthiness", "3", "none", "O(1)" },
	{ "over", "( a b -- a b a )", "Copy second over top", "5", "none", "O(1)" },
	{ "parallel-run", "( commands width -- results )", "lib.l4: run each argv array in commands as a subprocess, at most width at once; collect { :out :err :status } per command in input order, refilling a slot as each child finishes", "fork per command + poll", "1a + per-child frames/streams", "O(critical path)" },
	{ "pfilter", "( arr pred -- arr )", "Parallel filter, order preserved", "2 + n·xt", "malloc(n) flags + 1a(k)", "O(n·xt / w)" },
	{ "pfilter-ext", "( arr w c pred -- arr )", "pfilter with explicit worker count and items-per-claim", "2 + n·xt", "malloc(n) flags + 1a(k)", "O(n·xt / w)" },
	{ "pi", "( -- f )", "lib.l4: variable initialized to π (3.141592653589793); invoking it pushes the stored float", "1", "none", "O(1)" },
	{ "pmap", "( arr xt -- arr )", "Parallel map (num-cores workers, claim 1)", "2 + n·xt", "1a(n)", "O(n·xt / w)" },
	{ "pmap-ext", "( arr w c xt -- arr )", "pmap with explicit worker count and items-per-claim", "2 + n·xt", "1a(n)", "O(n·xt / w)" },
	{ "pmap-reduce", "( arr id map-xt combine-xt -- val )", "Fused parallel map+fold; combine-xt must be associative with id as neutral element", "2 + n·xt", "per-worker partials", "O(n·xt / w)" },
	{ "pmap-reduce-ext", "( arr w c id map-xt combine-xt -- val )", "pmap-reduce with explicit worker count and items-per-claim", "2 + n·xt", "per-worker partials", "O(n·xt / w)" },
	{ "query", "( rel pattern -- [rows] )", "Array of rows matching pattern; uses an index when the pattern grounds an indexed column, else scans. When every constraint is a ground indexed column the narrowed bucket *is* the answer, so the per-row matches? is skipped (covering query)", "candidates·n", "1a + set ops", "O(candidates·n)" },
	{ "quotient", "( a b -- quotient )", "lib.l4: % swap drop; toward zero", "9", "none", "O(1)" },
	{ "r>", "return stack → ( -- a )", "Move return-stack top to data stack", "2", "none", "O(1)" },
	{ "r@", "( -- a )", "Copy return-stack top to data stack", "2", "none", "O(1)" },
	{ "range", "( from to -- arr )", "Inclusive integer range, step ±1", "3 + n", "1a(n)", "O(n)" },
	{ "read", "( stream -- s )", "Read the stream to EOF into one string", "read syscalls", "1o + buffer growth", "O(bytes)" },
	{ "read-err", "( proc -- s )", "lib.l4: read the child's :err stream to EOF", "read syscalls", "1o + buffer growth", "O(bytes)" },
	{ "read-file", "( path -- s )", "Read a whole file as one string (byte-safe); errors if it can't be opened", "file read", "1o + buffer", "O(file)" },
	{ "read-out", "( proc -- s )", "lib.l4: read the child's :out stream to EOF", "read syscalls", "1o + buffer growth", "O(bytes)" },
	{ "reduce", "( arr/set init xt -- val )", "Left fold; xt is ( acc elem -- acc )", "3 + n·xt", "none", "O(n·xt)" },
	{ "reify", "( a -- a' )", "Like copy, but each unbound var becomes a canonical inert symbol :_0, :_1, … numbered by first appearance — a ground, storable, comparable snapshot.", "tree size", "one object per node", "O(tree size)" },
	{ "relation", "( [cols] -- rel )", "New empty relation; cols is an array of column symbols to index", "k", "frames + sets", "O(k)" },
	{ "reload", "( -- )", "Truncate user state, re-run every loaded file in order", "forget + N loads", "—", "O(Σ files)" },
	{ "repeat", "—", "Branch back to begin; patches the while exit", NULL, NULL, NULL },
	{ "replace", "( s pat rep -- s' )", "Replace **all** matches; in rep, & or \\0 is the whole match, \\1–\\9 a capture, \\& and \\\\ literals", "n", "1o + buffer growth", "O(n)" },
	{ "reset", "( -- )", "Push a unique mark on the return stack, delimiting the captured region", "1", "none", "O(1)" },
	{ "reshape", "( m r c -- m' )", "Same elements, new shape (must match); memcpy", "3 + r×c", "1m(r×c)", "O(r×c)" },
	{ "resume", "( k -- … )", "Pop k and re-enter it (multi-shot — the continuation object survives, so a retained copy can be resumed again); pushes whatever the resumed code yields", "L + resumed", "none", "O(L + resumed)" },
	{ "retract", "( rel pattern -- rel )", "Remove every row matching pattern from :rows and all buckets. Mutates rel, returns it", "matches·(k+n)", "1a", "O(matches·n)" },
	{ "reverse", "( arr/set -- arr )", "Reversed copy", "1 + n", "1a(n)", "O(n)" },
	{ "reverse-slice!", "( arr offset n -- arr )", "Reverse the n elements at offset in place; leaves arr", "2 + n", "none", "O(n)" },
	{ "roll", "( xₙ … x₀ n -- xₙ₋₁ … x₀ xₙ )", "Move the item n deep to the top; memmoves the n above it down", "2 + n", "none", "O(n)" },
	{ "rot", "( a b c -- b c a )", "Rotate top three", "6", "none", "O(1)" },
	{ "round", "( a -- round a )", "round", "2", "matrix 1m(r×c)", "same" },
	{ "round-down", "( a -- floor a )", "floor", "2", "matrix 1m(r×c)", "same" },
	{ "round-up", "( a -- ceil a )", "ceil", "2", "matrix 1m(r×c)", "same" },
	{ "row-maxes", "( m -- m' )", "r×1 of per-row maxima", "1 + r×c", "1m(r×1)", "O(r×c)" },
	{ "row-means", "( m -- m' )", "lib.l4: row-sums then scalar ÷", "r×c", "2×1m(r×1)", "O(r×c)" },
	{ "row-mins", "( m -- m' )", "r×1 of per-row minima", "1 + r×c", "1m(r×1)", "O(r×c)" },
	{ "row-sums", "( m -- m' )", "r×1 of per-row sums", "1 + r×c", "1m(r×1)", "O(r×c)" },
	{ "run", "( s -- proc )", "lib.l4: split a command string on runs of spaces and start-process it (\" +\" split start-process)", "split + fork", "1a + 1o frame + 3 streams", "O(|s| + argc)" },
	{ "running?", "( pid -- bool )", "Non-blocking liveness via waitid+WNOHANG+WNOWAIT; true while running, false once exited. Non-reaping, so a later wait still returns the status", "1 syscall", "none", "O(1)" },
	{ "save", "( s -- )", "Write all user words as re-loadable .l4 source", "dict scan + write", "file I/O", "O(|user dict|)" },
	{ "save-image", "( s -- )", "Binary snapshot of full state (dict, objects, stacks, continuations)", "serialize all", "file I/O", "O(objects + dict)" },
	{ "see", "( xt -- )", "Print a word's source (: name … ;), or variable/symbol/primitive form", "dict scan", "none", "O(|dict|)" },
	{ "see-compiled", "( xt -- )", "Disassemble a colon definition's compiled cells", "body scan", "none", "O(body)" },
	{ "select-keys", "( fr path -- arr )", "The full root-to-match path (a symbol array) for every match, document order; each round-trips through @", "s", "1a + 1a per match", "O(s + total path length)" },
	{ "select-values", "( fr path -- arr )", "Every matched value, in document (pre-order) order, duplicates kept; no path built per match", "s", "1a + reallocs", "O(s)" },
	{ "set", "( v₀ … vₙ₋₁ n -- set )", "Gather the top n values into a new set (the set analog of array)", "2 + n log n", "1o + reallocs", "O(n log n)" },
	{ "set-add!", "( set v -- set )", "Insert v in sorted position if absent (dedups); leaves set on the stack", "log n + n", "reallocs", "O(n)" },
	{ "set-remove!", "( set v -- set )", "Remove v if present (no-op if absent); leaves set on the stack", "log n + n", "none", "O(n)" },
	{ "shift", "( -- k )", "Capture the return-stack slice up to the nearest reset, remove the mark and that slice, push k", "L", "1o (cont)", "O(L)" },
	{ "shift-with", "( xt -- )", "Capture as shift, then run xt in the outer context with k on the stack and begin unwinding", "L + xt", "1o (cont)", "O(L + xt)" },
	{ "side-depth", "( -- n )", "Push side-stack depth", "1", "none", "O(1)" },
	{ "side-drop", "( -- )", "Discard side-stack top", "1", "none", "O(1)" },
	{ "side>", "( -- a )", "Pop from side stack", "2", "none", "O(1)" },
	{ "sin", "( a -- sin a )", "sine (radians)", "2", "matrix 1m(r×c)", "same" },
	{ "size", "( coll -- n )", "Element count of a set, array, or string; pair count of a frame", "2", "none", "O(1)" },
	{ "skip", "( arr n -- arr )", "lib.l4: over size swap - swap reverse swap take reverse", "3n", "3×1a(n)", "O(n)" },
	{ "sleep", "( seconds -- )", "Block for the given float seconds (sub-second supported); nanosleep", "blocks", "none", "O(1)" },
	{ "slice!", "( arr tstart src sstart sstep slen -- arr )", "Copy slen elements src[sstart], src[sstart+sstep], … into arr[tstart…] in place", "6 + slen", "self-overlap may malloc slen", "O(slen)" },
	{ "split", "( s pat -- [ piece… ] )", "Split s at each non-overlapping match of pat; the pieces are the gaps between matches, empty fields kept; no match → [ s ]", "n", "1a + pieces", "O(n)" },
	{ "sq", "( a -- a² )", "float or matrix", "2 (float)", "matrix 1m(r×c)", "float O(1); matrix O(r×c)" },
	{ "sqrt", "( a -- √a )", "sqrt", "2", "matrix 1m(r×c)", "same" },
	{ "start-generator", "( producer -- value generator )", "lib.l4: reset execute — run producer to its first yield; leaves the yielded value and a resumable continuation", "L", "1o (cont)", "O(producer to first yield)" },
	{ "start-process", "( argv -- proc )", "fork/exec argv[0] with argv as its arguments; return { :pid :in :out :err } (the three streams are T_STREAM)", "fork + 3 pipes", "1o frame + 3 streams", "O(argc)" },
	{ "stop", "( pid -- status )", "SIGKILL the child then reap it (137 = 128+9, or its code if it had already exited)", "2 syscalls", "none", "O(1)" },
	{ "string>symbol", "( s -- sym )", "Intern a computed string as a symbol", NULL, NULL, NULL },
	{ "substring", "( s start end -- sub )", "Half-open byte range [start, end); bounds-checked", "2 + k", "1o", "O(k), k = end − start" },
	{ "sum", "( m -- f )", "Sum of all elements (4-way unrolled, fast-math)", "1 + r×c", "none", "O(r×c)" },
	{ "swap", "( a b -- b a )", "Exchange top two", "4", "none", "O(1)" },
	{ "symbol", "—", "Read the following name; declare a word that pushes a specific interned symbol", NULL, NULL, NULL },
	{ "symbol?", "( v -- flag )", "True when v is a symbol", "2", "none", "O(1)" },
	{ "take", "( arr/set n -- arr )", "First n elements (clamped)", "2 + n", "1a(n)", "O(n)" },
	{ "tan", "( a -- tan a )", "tangent (radians)", "2", "matrix 1m(r×c)", "same" },
	{ "tanh", "( a -- tanh a )", "hyperbolic tangent", "2", "matrix 1m(r×c)", "same" },
	{ "then", "—", "Close an if/if…else; patches the forward branch", NULL, NULL, NULL },
	{ "throw", "( exc -- )", "lib.l4: [: drop 1 :] shift-with", "—", "1o (cont)", "O(stack depth)" },
	{ "times", "( xt n -- )", "Run xt n times, no index pushed", "2 + n·xt", "none", "O(n·xt)" },
	{ "to", "( val -- )", "Assign to the named local (in a definition) or global. At the REPL, auto-creates the global if absent. In a definition, the variable must already exist. May trigger superword store-fusion while compiling.", NULL, NULL, NULL },
	{ "to-slice!", "( v₀ … vₙ₋₁ arr offset n -- arr )", "Store the n values just below arr into arr[offset…offset+n); leaves arr", "2 + n", "none", "O(n)" },
	{ "transpose", "( m -- m' )", "Rows/columns swapped", "1 + r×c", "1m(c×r)", "O(r×c)" },
	{ "truncate", "( a -- trunc a )", "trunc", "2", "matrix 1m(r×c)", "same" },
	{ "try-catch", "( normal-xt err-xt -- … )", "lib.l4: run normal-xt; on throw, run err-xt with exc on the stack", "—", "cont if thrown", "O(normal-xt)" },
	{ "unify", "( a b -- term )", "Unify a and b, binding logic vars (recorded on the trail) so the two match, then leave the dereffed left term. Atoms by value; pairs head then tail; arrays element-wise; frames as open records — shared keys must unify, extra keys on either side allowed. A _ on either side matches anything and binds nothing. On a mismatch, fails.", "n", "none", "O(n)" },
	{ "union", "( s₁ s₂ -- s₃ )", "Union into a new set, merging the two sorted arrays", "m+n", "1o + reallocs", "O(m+n)" },
	{ "until", "( flag -- )", "Branch back to begin if flag is falsy", NULL, NULL, NULL },
	{ "update-at", "( fr sym/path xt -- fr )", "Apply xt to the value at the key, store the result back; errors on a search path", "d log n + xt", "none", "O(d log n + xt)" },
	{ "values", "( fr -- arr )", "Values in key order", "1 + n", "1a(n)", "O(n)" },
	{ "variable", "—", "Read the following name; declare a global variable initialized to 0.0", NULL, NULL, NULL },
	{ "vf*", "vf* a", "Multiply the stack top by variable a, in place", NULL, NULL, NULL },
	{ "vf+", "vf+ a", "Add variable a to the stack top, in place", NULL, NULL, NULL },
	{ "vf-", "vf- a", "Subtract variable a from the stack top, in place", NULL, NULL, NULL },
	{ "vf/", "vf/ a", "Divide the stack top by variable a, in place", NULL, NULL, NULL },
	{ "vfabs", "vfabs a", "Absolute value of variable a, push the result", NULL, NULL, NULL },
	{ "vfcos", "vfcos a", "cosine of variable a, push the result", NULL, NULL, NULL },
	{ "vfexp", "vfexp a", "eᵃ of variable a, push the result", NULL, NULL, NULL },
	{ "vflog", "vflog a", "base-10 log of variable a, push the result", NULL, NULL, NULL },
	{ "vfneg", "vfneg a", "Negate variable a, push the result", NULL, NULL, NULL },
	{ "vfsin", "vfsin a", "sine of variable a, push the result", NULL, NULL, NULL },
	{ "vfsq", "vfsq a", "Square variable a, push the result", NULL, NULL, NULL },
	{ "vfsqrt", "vfsqrt a", "Square root of variable a, push the result", NULL, NULL, NULL },
	{ "vftan", "vftan a", "tangent of variable a, push the result", NULL, NULL, NULL },
	{ "vftanh", "vftanh a", "hyperbolic tangent of variable a, push the result", NULL, NULL, NULL },
	{ "vvf*", "vvf* a b", "Load variables a and b, multiply, push the result", NULL, NULL, NULL },
	{ "vvf*+", "vvf*+ b c", "( t -- t*b+c ), reading variables b and c", NULL, NULL, NULL },
	{ "vvf*-", "vvf*- b c", "( t -- c-t*b ), reading variables b and c", NULL, NULL, NULL },
	{ "vvf+", "vvf+ a b", "Load variables a and b, add, push the result", NULL, NULL, NULL },
	{ "vvf-", "vvf- a b", "Load variables a and b, subtract (a−b), push the result", NULL, NULL, NULL },
	{ "vvf/", "vvf/ a b", "Load variables a and b, divide (a/b), push the result", NULL, NULL, NULL },
	{ "wait", "( pid -- status )", "Block until the child exits; return its exit code, or 128 + signo if it was killed by a signal", "blocks", "none", "O(1)" },
	{ "while", "( flag -- )", "Exit the loop forward if flag is falsy (begin … while … repeat)", NULL, NULL, NULL },
	{ "words", "( -- )", "List all non-internal words, newest first, 8 per line", "dict scan", "none", "O(|dict|)" },
	{ "write", "( s stream -- )", "Write the string's bytes to the stream; loops over partial writes, retries EINTR", "write syscalls", "none", "O(|s|)" },
	{ "write-file", "( s path -- )", "Create or truncate the file, then write the string's bytes", "file write", "none", "O(|s|)" },
	{ "write-in", "( s proc -- )", "lib.l4: write the string to the child's :in stream", "write syscalls", "none", "O(|s|)" },
	{ "yield", "( v -- resumed )", "lib.l4: shift — emit v to the driver; returns whatever the driver passes back via resume", "L", "1o (cont)", "O(L)" },
	{ "~", "( a b -- term )", "lib.l4: unify (inlined)", "n", "none", "O(n)" },
};

const int help_entry_count = 301;
