#include "water.h"

const char *const help_section_names[] = {
	"Stack manipulation",
	"Arithmetic",
	"Constants",
	"Unary math (polymorphic: float or matrix)",
	"Comparison and logic",
	"Dimensioned quantities",
	"Return stack",
	"Side stack",
	"Control flow (compile-time)",
	"Delimiters",
	"Defining and compiling words",
	"I/O and printing",
	"String operations",
	"Sets",
	"Arrays",
	"Pairs (cons lists)",
	"Frames",
	"JSON",
	"Matrices",
	"Segments",
	"Random",
	"Wall-clock time and dates",
	"Datasets and TSV",
	"Higher-order",
	"Delimited continuations",
	"Generators",
	"Logic",
	"Fact database",
	"Superwords (compile-time fusion) ⚠",
	"REPL and introspection",
	"Persistence",
	"Files and environment",
	"Subprocesses and streams",
	"SQLite",
	"Foreign function interface",
	"Type tags",
	"Object allocation",
};

const int help_section_count = 37;

const HelpEntry help_entries[] = {
	{ "!", "( fr sym/path val -- fr )", "Set by key or path, vivifying intermediates; mutates fr; errors on a search path", "d log n", "realloc on growth; 1o per vivified frame", "O(d log n) amortized", 16 },
	{ "!e", "( m i v -- m )", "Store v (a float, or null for NaN) at flat row-major index i, in place", "4", "none", "O(1)", 18 },
	{ "!i", "( arr i val -- arr )", "Store val at index i in place; leaves arr on the stack", "4", "none", "O(1)", 14 },
	{ "!i,j", "( m i j v -- m )", "Store v (a float, or null for NaN) at row i, column j, in place", "5", "none", "O(1)", 18 },
	{ "%", "( a b -- remainder quotient )", "floats only; truncating division: pushes a − trunc(a/b)·b then trunc(a/b); errors on zero", "4", "none", "O(1)", 1 },
	{ "'", "( \"name\" -- xt )", "Parse the following word at compile time and push its xt (immediate; folds the xt in as a literal)", NULL, NULL, NULL, 10 },
	{ ")]", "—", "Close a cons-list literal", NULL, NULL, NULL, 9 },
	{ "*", "( a b -- a*b )", "float: multiply. set∩set: intersection. matrix: element-wise. scalar/matrix broadcast.", "3 (float)", "as +", "as +", 1 },
	{ "*!", "( m a -- m )", "in-place multiply", "3 + r×c", "none", "O(r×c)", 1 },
	{ "+", "( a b -- a+b )", "float: add. string+string: concat → new string. set+set: union → new set. matrix+matrix: element-wise → new matrix. scalar+matrix / matrix+scalar: broadcast → new matrix. array+array: defers to concat.", "3 (float)", "float none; string 1s + temp buffer; set 1o; matrix 1m(r×c); array 1a(m+n)", "float O(1); string O(|s|); set O(n log n); matrix O(r×c); array O(m+n)", 1 },
	{ "+!", "( m a -- m )", "matrix+matrix or matrix+scalar (and scalar+matrix, mutating the matrix) in place", "3 + r×c", "none", "O(r×c)", 1 },
	{ "++", "( -- )", "Increment the named local by 1 in place", "1", "none", "O(1)", 10 },
	{ "-", "( a b -- a-b )", "float: subtract. set−set: difference. matrix: element-wise. scalar/matrix broadcast.", "3 (float)", "as +", "as +", 1 },
	{ "-!", "( m a -- m )", "in-place subtract", "3 + r×c", "none", "O(r×c)", 1 },
	{ "--", "( -- )", "Decrement the named local by 1 in place", "1", "none", "O(1)", 10 },
	{ ".", "( a -- )", "Print value then a space; matrices print as a grid, frames pretty-print", "1 + print", "none", "O(size printed)", 11 },
	{ ".a", "( a -- )", "Like . but disables print truncation (show all elements)", "1 + print", "none", "O(size printed)", 11 },
	{ ".s", "( -- )", "Print every stack value, bottom to top; leaves the stack intact", "print", "none", "O(depth)", 11 },
	{ "/", "( a b -- a/b )", "float: divide (errors on zero divisor). matrix÷matrix: element-wise (errors on any zero element). scalar/matrix broadcast.", "3 (float)", "matrix 1m(r×c)", "float O(1); matrix O(r×c)", 1 },
	{ "/!", "( m a -- m )", "in-place divide", "3 + r×c", "none", "O(r×c)", 1 },
	{ "0-matrix", "( r c -- m )", "r×c zero matrix (calloc)", "3", "1m(r×c)", "O(1)+", 18 },
	{ "0=", "( a -- bool )", "!truthy(a); any type", "2", "none", "O(1)", 4 },
	{ "1+", "( a -- a+1 )", "float or matrix", "2 (float)", "matrix 1m(r×c)", "float O(1); matrix O(r×c)", 1 },
	{ "1-", "( a -- a-1 )", "float or matrix", "2 (float)", "matrix 1m(r×c)", "float O(1); matrix O(r×c)", 1 },
	{ "2drop", "( a b -- )", "core.h2o: drop drop (inlined)", "6", "none", "O(1)", 0 },
	{ "2dup", "( a b -- a b a b )", "core.h2o: over over (inlined)", "10", "none", "O(1)", 0 },
	{ ":", "—", "Begin a colon definition; read the following name; enter compile mode", NULL, NULL, NULL, 10 },
	{ ":]", "—", "Close a quotation (any [: / [| / [> form; [: itself is under Defining)", NULL, NULL, NULL, 9 },
	{ ":name", "( -- sym )", "Symbol literal; interns the name at read time", NULL, NULL, NULL, 10 },
	{ ";", "—", "End a colon definition; emit exit; store the source text for see. Self-delimiting: dup *; parses", NULL, NULL, NULL, 10 },
	{ "<", "—", "Open a set literal; > closes it (both need surrounding spaces)", NULL, NULL, NULL, 9 },
	{ "=", "( a b -- bool )", "structural equality", "3 (float)", "none", "float O(1); string O(|s|); array/set O(n); frame O(n); matrix O(r×c)", 4 },
	{ ">", "—", "Close a set literal", NULL, NULL, NULL, 9 },
	{ ">r", "( a -- ) → return stack", "Move top to return stack", "2", "none", "O(1)", 6 },
	{ ">side", "( a -- )", "Push to side stack", "2", "none", "O(1)", 7 },
	{ "?", "( v -- val )", "logic.h2o: deref (inlined)", "d", "none", "O(d)", 26 },
	{ "?if", "( flag -- flag )", "Like if, but peeks the flag instead of consuming it — the flag stays on the stack in both branches", NULL, NULL, NULL, 8 },
	{ "@", "( fr sym/path -- val )", "Get by key or path; errors if absent or if the path is a search path", "3 + d log n", "none", "O(d log n)", 16 },
	{ "@e", "( m i -- f )", "Element at flat row-major index i as a float — consumes argmin/argmax/where indices; the same access on n×1 and 1×n vectors", "3", "none", "O(1)", 18 },
	{ "@i", "( arr i -- val )", "Array element; on a matrix returns row i as a 1×c matrix", "3 (array)", "matrix 1m(1×c)", "O(1) array; O(c) matrix", 14 },
	{ "@i,j", "( m i j -- f )", "Single element as a float", "4", "none", "O(1)", 18 },
	{ "@j", "( m j -- col )", "Column j as an r×1 matrix (copy)", "2 + r", "1m(r×1)", "O(r)", 18 },
	{ "@or", "( fr sym/path fallback -- val )", "Get by key or path, the fallback when absent — has? if @ in one probe, no error on miss; the fallback is already evaluated, so it suits values, not expensive computations", "4 + d log n", "none", "O(d log n)", 16 },
	{ "C", "( -- q )", "Speed of light, 299792458 m/s (exact)", NULL, NULL, NULL, 2 },
	{ "E", "( -- f )", "Euler's number e", NULL, NULL, NULL, 2 },
	{ "G", "( -- q )", "Gravitational constant, 6.67430×10⁻¹¹ m³·kg⁻¹·s⁻²", NULL, NULL, NULL, 2 },
	{ "H", "( -- q )", "Planck constant, 6.62607015×10⁻³⁴ J·s (exact)", NULL, NULL, NULL, 2 },
	{ "HBAR", "( -- q )", "Reduced Planck constant h/2π", NULL, NULL, NULL, 2 },
	{ "KB", "( -- q )", "Boltzmann constant, 1.380649×10⁻²³ J/K (exact)", NULL, NULL, NULL, 2 },
	{ "NA", "( -- q )", "Avogadro constant, 6.02214076×10²³ mol⁻¹ (exact)", NULL, NULL, NULL, 2 },
	{ "PHI", "( -- f )", "The golden ratio (1+√5)/2", NULL, NULL, NULL, 2 },
	{ "PI", "( -- f )", "π", NULL, NULL, NULL, 2 },
	{ "QE", "( -- q )", "Elementary charge, 1.602176634×10⁻¹⁹ C (exact)", NULL, NULL, NULL, 2 },
	{ "TAU", "( -- f )", "2π", NULL, NULL, NULL, 2 },
	{ "[", "—", "Open an array literal; ] closes it", NULL, NULL, NULL, 9 },
	{ "[(", "—", "Open a cons-list literal; )] closes it", NULL, NULL, NULL, 9 },
	{ "[:", "( -- xt )", "Open an anonymous quotation (closed by :]); compiles its body and pushes its xt", NULL, NULL, NULL, 10 },
	{ "[>", "—", "Open a quotation whose locals list receives every slot from the stack", NULL, NULL, NULL, 9 },
	{ "[|", "—", "Open a quotation whose body starts with a | … | locals list", NULL, NULL, NULL, 9 },
	{ "]", "—", "Close an array literal", NULL, NULL, NULL, 9 },
	{ "^", "( a b -- a^b )", "pow; float or matrix (element-wise) / scalar broadcast", "3 (float)", "matrix 1m(r×c)", "float O(1); matrix O(r×c)", 1 },
	{ "_", "( -- wild )", "The anonymous wildcard — unifies with anything, binds nothing, allocates nothing (a constant, not a fresh var)", "2", "none", "O(1)", 26 },
	{ "abs", "( a -- |a| )", "fabs", "2 (float)", "matrix 1m(r×c)", "float O(1); matrix O(r×c)", 3 },
	{ "acos", "( a -- acos a )", "inverse cosine", "2", "matrix 1m(r×c)", "same", 3 },
	{ "add-last!", "( arr v -- arr )", "Append v at the end, doubling the backing buffer when full; leaves arr on the stack", "2", "≤1a on grow", "amortized O(1)", 14 },
	{ "again", "—", "Unconditional branch back to begin", NULL, NULL, NULL, 8 },
	{ "all?", "( items pred -- bool )", "arrays.h2o: false at the first element failing pred, else true (vacuously true on empty)", "n·xt", "none", "O(n·xt)", 23 },
	{ "alloc-stats", "( -- )", "Print and reset the allocation counters since the last call (lvars=… arrays=…)", "2", "none", "O(1)", 29 },
	{ "amb", "( xt1 xt2 -- … )", "Run xt1; if it fails (a unify mismatch or fail), roll its bindings back through the trail and run xt2. Commits to the first branch that succeeds.", "xt1", "none", "O(xt1 + xt2)", 26 },
	{ "and", "( a b -- bool )", "logical and of truthiness", "3", "none", "O(1)", 4 },
	{ "any?", "( items pred -- bool )", "arrays.h2o: find none? not", "n·xt", "none", "O(n·xt)", 23 },
	{ "append-file", "( s path -- )", "Open in append mode, write the string's bytes", "file write", "none", "O(|s|)", 31 },
	{ "apropos", "( s -- )", "Print every word whose name or reference summary contains s (case-insensitive): name, stack effect, summary per line; session-defined words match by name", "table scan", "none", "O(entries)", 29 },
	{ "argmax", "( m -- f )", "Flat row-major index of the maximum element (first on ties)", "1 + r×c", "none", "O(r×c)", 18 },
	{ "argmin", "( m -- f )", "Flat row-major index of the minimum element (first on ties)", "1 + r×c", "none", "O(r×c)", 18 },
	{ "argsort", "( v -- v' )", "The sorting permutation of a vector, shape preserved: element i is the source index of the i-th smallest value; ties keep index order, NaNs go last in index order; ranks are argsort twice", "1 + n log n", "1m(n) + malloc(16n)", "O(n log n); above 8k elements O(n) radix", 18 },
	{ "array", "( v₀ … vₙ₋₁ n -- arr )", "Gather the top n values into an array", "2 + n", "1a(n)", "O(n)", 14 },
	{ "array-of", "( val n -- arr )", "New n-element array, every slot = val", "3 + n", "1a(n)", "O(n)", 14 },
	{ "array>cons", "( arr -- list )", "Cons chain from an array's elements (last element becomes the tail; [ ] → null)", "n", "n−1 pairs", "O(n)", 15 },
	{ "array>frame", "( arr -- fr )", "Build from an even-length alternating-kv array; a path key (/a/b/c) vivifies nested frames", "1 + n log n", "1o + reallocs", "O(n log n)", 16 },
	{ "array>set", "( array -- set )", "Sort a copy of the array once and dedup into a set — the fast bulk constructor (one sort, not n inserts); the source array is unchanged", "n log n", "1o + realloc", "O(n log n)", 13 },
	{ "array?", "( a -- bool )", "core.h2o: type-of :array = (inlined)", "5", "none", "O(1)", 4 },
	{ "as-column", "( v -- v' )", "matrix.h2o: any vector shape as n×1 (dup dim * 1 reshape, inlined)", "r×c", "1m(n×1)", "O(n)", 18 },
	{ "asin", "( a -- asin a )", "inverse sine", "2", "matrix 1m(r×c)", "same", 3 },
	{ "assert", "( rel row -- rel )", "Add row to :rows and to each indexed column's bucket; identical row is a no-op. Mutates rel in place, returns it", "k + n", "reallocs", "O(n)", 27 },
	{ "atan", "( a -- atan a )", "inverse tangent", "2", "matrix 1m(r×c)", "same", 3 },
	{ "augment", "( a b -- m )", "Concatenate two matrices column-wise; errors unless row counts match", "2 + r·c", "1m(r×c)", "O(r·c)", 18 },
	{ "base", "( -- q )", "Push a base quantity — a fresh dimension with its base unit, magnitude 1.0. Paired with unit to declare a base dimension (base unit m)", NULL, NULL, NULL, 10 },
	{ "basename", "( path -- filename )", "strings.h2o: the path's last component (\"^.*/\" \"\" replace, inlined); a path with no / passes through", "n", "1o", "O(n)", 12 },
	{ "begin", "—", "Mark a loop top", NULL, NULL, NULL, 8 },
	{ "bit-and", "( a b -- f )", "bitwise AND", "2", "none", "O(1)", 4 },
	{ "bit-not", "( a -- f )", "two's-complement complement", "1", "none", "O(1)", 4 },
	{ "bit-or", "( a b -- f )", "bitwise OR", "2", "none", "O(1)", 4 },
	{ "bit-xor", "( a b -- f )", "bitwise XOR", "2", "none", "O(1)", 4 },
	{ "bootstrap", "( data fit-xt B -- arr )", "statistics.h2o: B refits of fit-xt over row-resamples of data. One serial draw sets the run seed; replicate i draws its indices via resample-indices-ext at run-seed + i, so no resample outlives its fit and results don't depend on scheduling — deterministic under a fixed seed", "B(n + fit)", "per-fit resample + 1a(B)", "O(B·(n + fit))", 18 },
	{ "bootstrap-with", "( data fit-xt B mapper-xt -- arr )", "statistics.h2o: the bootstrap skeleton bootstrap/pbootstrap instantiate; mapper-xt is map-shaped", "as bootstrap", "as bootstrap", "as bootstrap", 18 },
	{ "bulk-load", "( rel rows-array -- rel )", "Load all rows at once: builds :rows (a deduped set) and each declared column's index, instead of row-by-row", "—", "sets + frame", "O(n log n)", 27 },
	{ "bye", "( -- )", "exit(0)", "—", "—", "—", 29 },
	{ "byte-size", "( s -- n )", "Byte length of a string", "2", "none", "O(1)", 13 },
	{ "byte-substring", "( s start end -- sub )", "Half-open **byte** range [start, end); bounds-checked. Pairs with byte offsets from match/match-all", "2 + k", "1o", "O(k), k = end − start", 12 },
	{ "catch", "( xt -- result 0 | exc 1 )", "exceptions.h2o: reset (execute-catching) 0; (result 0) on success, (exc 1) on a throw **or** an interpreter error (an error frame { :message :trace } becomes the exception value)", "—", "cont if thrown; 1f + 2s on a caught interpreter error", "O(xt)", 24 },
	{ "cd", "( path -- )", "Change the interpreter's working directory (chdir); process-wide, so it moves the base for relative file I/O and is inherited by subsequent start-process children", "1", "none", "O(1)", 31 },
	{ "char-at", "( s index -- char )", "The one-character string at codepoint index; bounds-checked against the codepoint count", "2 + n", "1o", "O(n)", 12 },
	{ "choose", "( list cont -- )", "logic.h2o: run cont with each element of a cons list in turn, committing to the first for which it succeeds; fail if none do (n-way amb over a list)", "n·cont", "none", "O(n·cont)", 26 },
	{ "ci", "( m level -- low high )", "statistics.h2o: percentile confidence interval — level 0.95 gives the 0.025 and 0.975 quantiles", "2n log n", "malloc(n) ×2", "O(n log n)", 18 },
	{ "clear", "( … -- )", "Reset data stack depth to 0", "1", "none", "O(1)", 0 },
	{ "close", "( stream -- )", "Close the fd; closing a child's :in sends it EOF", "1 syscall", "none", "O(1)", 32 },
	{ "codepoint-at", "( s index -- code )", "The integer codepoint at codepoint index; bounds-checked", "2 + n", "none", "O(n)", 12 },
	{ "codepoint>char", "( code -- char )", "One-character string for codepoint code; range-checked [0, 0x10FFFF]", "1", "1o", "O(1)", 12 },
	{ "codepoints>string", "( [ code… ] -- s )", "Encode each codepoint to UTF-8 and concatenate; per-element type- and range-checked", "n", "1o", "O(n)", 12 },
	{ "column-maxes", "( m -- m' )", "1×c of per-column maxima", "1 + r×c", "1m(1×c)", "O(r×c)", 18 },
	{ "column-means", "( m -- m' )", "matrix.h2o: column-sums then scalar ÷", "r×c", "2×1m(1×c)", "O(r×c)", 18 },
	{ "column-mins", "( m -- m' )", "1×c of per-column minima", "1 + r×c", "1m(1×c)", "O(r×c)", 18 },
	{ "column-sums", "( m -- m' )", "1×c of per-column sums", "1 + r×c", "1m(1×c)", "O(r×c)", 18 },
	{ "concat", "( arr/set arr/set -- arr )", "Concatenated copy", "2 + m + n", "1a(m+n)", "O(m+n)", 14 },
	{ "cons", "( head tail -- pair )", "Build a cons cell", "2", "1 pair", "O(1)", 15 },
	{ "cons>array", "( list -- arr )", "Walk a cons chain into an array, **dereferencing** the spine and each element and including the terminal (works on relational results)", "n", "1a(n)", "O(n)", 15 },
	{ "constant", "( val -- )", "Pop a value and read the following name; define an inline word that pushes it as a literal, so call sites fold to the literal with no run-time fetch. Fixed at definition — to cannot reassign it", NULL, NULL, NULL, 10 },
	{ "continuation?", "( a -- bool )", "core.h2o: type-of :continuation = (inlined)", "5", "none", "O(1)", 4 },
	{ "continue", "—", "Branch back to the innermost loop's begin: a while loop re-runs its test; an until loop skips its trailing test and repeats unconditionally", NULL, NULL, NULL, 8 },
	{ "copy", "( a -- a' )", "Deep copy of any value, copy_term-style: dereferences bound logic vars to their values and gives each unbound var a fresh shared var; recurses into frames, arrays, matrices, strings, sets, continuations, pairs; identity for scalars. Defined generally, not frame-specific.", "tree size", "one object per node", "O(tree size)", 16 },
	{ "cor", "( xs ys -- fr )", "statistics.h2o: correlation-kendall with a 500-replicate bootstrap CI — ' correlation-kendall 500 correlate-with (inlined)", "as correlate-with", "as correlate-with", "as correlate-with", 18 },
	{ "correlate-with", "( xs ys xt B -- fr )", "statistics.h2o: bootstrap 95% CI for the correlation word at xt — resamples (x, y) pairs jointly, B refits via a curried fit through pbootstrap, as { :estimate :se :bias :ci-low :ci-high }; deterministic under a fixed seed", "B·(n + xt)", "pairs matrix + per-worker resample + 1fr", "O(B·(n + xt) / cores)", 18 },
	{ "correlation-kendall", "( xs ys -- f )", "Kendall tau-b: concordant minus discordant pairs over sqrt of tie-corrected pair counts, via one (x,y) sort and a merge-sort exchange count; NaN when all x or all y are tied; errors on length mismatch or fewer than 2 elements", "2n log n", "malloc(16n) ×2–3", "O(n log n); above 8k elements the pair sort is O(n) radix", 18 },
	{ "correlation-pearson", "( xs ys -- f )", "statistics.h2o: Pearson r — center both vectors, then dot products for covariance and the two variances; accepts nx1 or 1xn; null when either vector is constant (R's NA)", "12n", "6m(n)", "O(n)", 18 },
	{ "correlation-spearman", "( xs ys -- f )", "statistics.h2o: Spearman rho — correlation-pearson on the ranks of both vectors (inlined); tied values take index-order ranks, so heavily tied data drifts from the midrank definition", "2n log n", "4m(n) + malloc(16n) ×2", "O(n log n)", 18 },
	{ "cos", "( a -- cos a )", "cosine (radians)", "2", "matrix 1m(r×c)", "same", 3 },
	{ "count-matches", "( rel pattern -- n )", "How many rows match; for a covering query this is the bucket's size with no scan, otherwise query size", "—", "(covering: none)", "O(candidates)", 27 },
	{ "cr", "( -- )", "Print a newline", "1", "none", "O(1)", 11 },
	{ "create-index", "( rel cols -- rel )", "Index a relation on the symbol columns cols: intern each indexed column's value to a symbol (so it keys the bucket and matches a { :col :val } pattern), then load-bag into a cols-indexed relation. Other columns keep their type; :rows stays a bag. The explicit bridge from a db-query result to an indexed relation", "n", "frame + sets", "O(n)", 27 },
	{ "cumulative-sum", "( m -- m' )", "Running sum over the elements in row-major order, shape preserved — a vector's prefix sums (ecdf, ROC, and calibration plumbing)", "1 + n", "1m(r×c)", "O(n)", 18 },
	{ "curry", "( value xt -- xt' )", "Bind a value into a new anonymous word: xt' pushes value, then calls xt. Compiles ~10 permanent dictionary cells per call (reclaimed only by forget); errors inside a parallel region — curry before pmap, execute freely within", NULL, NULL, NULL, 10 },
	{ "cwd", "( -- path )", "The interpreter's current working directory as a string (getcwd)", "1", "1o", "O(|path|)", 31 },
	{ "dataset>matrix", "( dataset cols -- m )", "datasets.h2o: build an n×k matrix from the named numeric columns (rows are observations)", "n·k", "flat 1a(n·k) + 2m(n×k)", "O(n·k)", 22 },
	{ "date-shift", "( instant delta -- instant )", "units.h2o: calendar shift, UTC. :years/:months step the calendar with the day clamped to the target month (Jan 31 + 1 month = Feb 28/29); :weeks :days :hours :minutes :seconds add exact durations. Components combine and may be negative", "200", "frames + pairs", "O(1)", 21 },
	{ "date>epoch", "( date -- instant )", "Compose an instant from a date frame, UTC; :year required, absent fields default, out-of-range fields carry", "30", "1 pair", "O(1)", 21 },
	{ "date>epoch-local", "( date -- instant )", "Compose via mktime in the process's timezone; the zone rules resolve DST", "30", "1 pair", "O(1)", 21 },
	{ "days-in-month", "( year month -- days )", "units.h2o: length of the month, leap-aware (first of next month minus first of this)", "60", "frames", "O(1)", 21 },
	{ "db-close", "( db -- )", "Close the connection and free its registry slot. Idempotent — closing an already-closed handle is a no-op. A handle that is dropped without closing leaks the connection until process exit", "1 syscall", "none", "O(1)", 33 },
	{ "db-exec", "( db statement params -- n )", "Bind params to the statement's ? placeholders and run it with no result set (INSERT / UPDATE / DELETE / CREATE / …); return the affected-row count as a float (0 for DDL). One statement per call. On a bad statement, errors with SQLite's message", "per statement", "none", "O(statement)", 33 },
	{ "db-open", "( path -- db )", "Open (creating if absent) the database file at path and push a handle; \":memory:\" is a private in-memory database. Errors if it can't be opened", "open", "1 connection (not GC'd)", "O(1)+", 33 },
	{ "db-query", "( db query params -- rel )", "Bind params to the query's ? placeholders and run it; return an index-less relation { :rows <array of row frames> :index { } }. Each row is a frame keyed by column-name symbols, with INTEGER/REAL → float, TEXT → string, NULL → null, BLOB → string of raw bytes. :rows is a **bag** — duplicates kept, in result order. On a bad query, errors with SQLite's message", "n·c", "1o relation + 1a(n) + 1o/row + a string per text/blob cell", "O(n·c)", 33 },
	{ "db-query>dataset", "( db query params -- dataset )", "database.h2o: the same query, returned as a column-oriented dataset with **typed columns**: a column whose every cell is numeric or NULL becomes an n×1 vector (NULL → NaN), a column declared DATE/DATETIME/TIMESTAMP becomes a vector of instants in s (numeric cells read as epoch seconds, text cells parsed as ISO Z), and anything else stays an array with none for NULL. An empty column declared numeric stays an empty vector, so the type survives an empty result; a repeated column name keeps its last occurrence. The C primitive (db-query>dataset) returns the raw columns plus each column's declared type from the same prepared statement", "n·c", "1o frame + 1a/column + 1m per numeric column + a string per text cell", "O(n·c)", 33 },
	{ "db?", "( a -- bool )", "core.h2o: type-of :db = (inlined)", "5", "none", "O(1)", 4 },
	{ "delete-at", "( fr sym/path -- fr )", "Remove a key (errors if absent or on a search path); mutates fr", "n", "none", "O(n)", 16 },
	{ "depth", "( -- n )", "Push current depth", "1", "none", "O(1)", 0 },
	{ "deref", "( v -- val )", "Follow a logic var's binding chain to the first non-variable value (v itself if unbound). Shallow — a returned structure still has bound vars inside; for a fully resolved snapshot use reify or copy", "d", "none", "O(d)", 26 },
	{ "destruct", "( arr/set/fr -- v… )", "Spread elements onto the stack; a frame spreads alternating sym/value", "1 + n", "none", "O(n)", 14 },
	{ "destruct-to", "( source targets -- )", "source and target arrays; assign each source element to the variable named by the corresponding target (symbol or xt), creating it if needed", "2 + n", "may create variables", "O(n)", 14 },
	{ "dgemm-nn", "( α A B β C -- R )", "R = α·A·B + β·C, ikj fast path", "5 + m·k·n", "1m(m×n)", "O(m·k·n)", 18 },
	{ "dgemm-nt", "( α A B β C -- R )", "R = α·A·Bᵀ + β·C", "5 + m·k·n", "1m(m×n)", "O(m·k·n)", 18 },
	{ "dgemm-tn", "( α A B β C -- R )", "R = α·Aᵀ·B + β·C", "5 + m·k·n", "1m(m×n)", "O(m·k·n)", 18 },
	{ "dgemm-tt", "( α A B β C -- R )", "R = α·Aᵀ·Bᵀ + β·C", "5 + m·k·n", "1m(m×n)", "O(m·k·n)", 18 },
	{ "diagonal", "( m -- m' )", "Diagonal as a 1×min(r,c) matrix", "1 + min(r,c)", "1m(1×min)", "O(min(r,c))", 18 },
	{ "diagonal-matrix", "( fill n -- m )", "n×n matrix with fill on the diagonal", "2 + n", "1m(n×n)", "O(n)", 18 },
	{ "difference", "( s₁ s₂ -- s₃ )", "s₁ − s₂ into a new set, merging the two sorted arrays", "m+n", "1o + reallocs", "O(m+n)", 13 },
	{ "dim", "( m -- r c )", "Push rows then columns", "3", "none", "O(1)", 18 },
	{ "dot", "( v w -- f )", "matrix.h2o: inner product (* sum, inlined); shapes must broadcast, so match the vectors", "2 + 2n", "1m(n)", "O(n)", 18 },
	{ "double-segment", "( n -- seg )", "n-element double segment, zero-filled; errors if n < 0", "1", "1seg(n)", "O(n)", 19 },
	{ "drop", "( a -- )", "Discard top", "1", "none", "O(1)", 0 },
	{ "drop-nans", "( v -- v' )", "matrix.h2o: the finite elements of a vector, NaNs dropped (dup nan? 0 eq where select-rows, inlined)", "4n", "mask + index + 1m(k)", "O(n)", 18 },
	{ "dup", "( a -- a a )", "Duplicate top", "3", "none", "O(1)", 0 },
	{ "each", "( items xt -- )", "arrays.h2o: run xt ( element -- ) on every element for its side effects; no result, no allocation", "n·xt", "none", "O(n·xt)", 23 },
	{ "else", "—", "Separate the true and false arms", NULL, NULL, NULL, 8 },
	{ "emit", "( code -- )", "Print the character with codepoint code, UTF-8 encoded (1–4 bytes); range-checked [0, 0x10FFFF]", "1", "none", "O(1)", 11 },
	{ "end-process", "( proc -- )", "subprocess.h2o: the teardown mirror of start-process — close :in/:out/:err and wait :pid (graceful, blocks until exit)", "3 closes + wait", "none", "O(1)", 32 },
	{ "ensure", "( body-xt cleanup-xt -- … )", "exceptions.h2o: run cleanup-xt (stack-neutral) whether body-xt returns normally or throws/errors, then re-raise on the throw path", "—", "cont if thrown", "O(body-xt)", 24 },
	{ "env", "( name -- val )", "Environment variable as a string, or the none value if unset (so set-empty \"\" and unset stay distinct)", "1", "1o on hit", "O(|val|)", 31 },
	{ "env!", "( name value -- )", "Set an environment variable (overwriting); process-wide, so subsequent start-process children inherit it", "1", "none", "O(1)", 31 },
	{ "epoch>date", "( instant -- date )", "Decompose an instant into a date frame, UTC", "40", "1o", "O(1)", 21 },
	{ "epoch>date-local", "( instant -- date )", "Decompose in the process's timezone", "40", "1o", "O(1)", 21 },
	{ "eq", "( a b -- bool ) or ( m x -- m )", "equality; element-wise 1/0 matrix on matrix operands (scalar broadcast) — the mask-producing twin of =, which stays structural on matrices; off matrices the two agree. NaN elements equal nothing", "3 (float)", "matrix 1m(r×c)", "same; matrix O(r×c)", 4 },
	{ "execute", "( xt -- … )", "Call the word at xt", NULL, NULL, NULL, 10 },
	{ "exit", "( -- )", "Return early from the current definition (this one runs at run time)", NULL, NULL, NULL, 8 },
	{ "exp", "( a -- eᵃ )", "exp", "2", "matrix 1m(r×c)", "same", 3 },
	{ "f*", "( a b -- a*b ) ⚠", "multiply", "2", "none", "O(1)", 1 },
	{ "f*+", "( a b c -- a*b+c ) ⚠", "fused multiply-add; result in slot of a", "3", "none", "O(1)", 1 },
	{ "f*-", "( a b c -- c-a*b ) ⚠", "fused multiply-subtract", "3", "none", "O(1)", 1 },
	{ "f+", "( a b -- a+b ) ⚠", "add, result in deeper slot", "2", "none", "O(1)", 1 },
	{ "f++", "( -- ) ⚠", "Unsafe float increment: raw .number mutation, no tag check, for a local known to hold a float", "1", "none", "O(1)", 10 },
	{ "f-", "( a b -- a-b ) ⚠", "subtract", "2", "none", "O(1)", 1 },
	{ "f--", "( -- ) ⚠", "Unsafe float decrement: raw .number mutation, no tag check", "1", "none", "O(1)", 10 },
	{ "f/", "( a b -- a/b ) ⚠", "divide; checks divisor ≠ 0", "2", "none", "O(1)", 1 },
	{ "f1+", "( a -- a+1 ) ⚠", "in place", "1", "none", "O(1)", 1 },
	{ "f1-", "( a -- a-1 ) ⚠", "in place", "1", "none", "O(1)", 1 },
	{ "f^", "( a b -- a^b ) ⚠", "pow", "2", "none", "O(1)", 1 },
	{ "fabs", "( a -- |a| ) ⚠", "in place", "1", "none", "O(1)", 1 },
	{ "facos", "( a -- acos a ) ⚠", "inverse cosine, in place", "1", "none", "O(1)", 1 },
	{ "fail", "( -- )", "Backtrack to the nearest enclosing amb, failing the current branch; with no enclosing amb, an error", "1", "none", "O(L)", 26 },
	{ "false", "( -- bool )", "core.h2o: pushes 0 (inline)", "1", "none", "O(1)", 4 },
	{ "fasin", "( a -- asin a ) ⚠", "inverse sine, in place", "1", "none", "O(1)", 1 },
	{ "fatan", "( a -- atan a ) ⚠", "inverse tangent, in place", "1", "none", "O(1)", 1 },
	{ "fcos", "( a -- cos a ) ⚠", "cosine (radians), in place", "1", "none", "O(1)", 1 },
	{ "feq", "( a b -- f ) ⚠", "float =, result 1.0/0.0; no type check", "2", "none", "O(1)", 1 },
	{ "fexp", "( a -- eᵃ ) ⚠", "in place", "1", "none", "O(1)", 1 },
	{ "ffi-free", "( ptr -- )", "free a C buffer held as a T_PTR (e.g. from malloc) and clear its registry slot. Not for library handles", "free", "none", "O(1)", 34 },
	{ "ffi-function", "( lib symbol arg-types ret-type -- ) <name>", "Resolve symbol in lib, build a libffi call interface, and define the following word <name> to call it. arg-types is an array of type symbols, ret-type a single symbol. The interface is prepared once; calls are ~30–100 ns", "dlsym + prep_cif", "1 binding", "O(argc)", 34 },
	{ "ffi-open", "( path -- lib )", "dlopen the library at path and push a T_PTR handle; \"\" opens the running process itself (dlopen(NULL)) for already-linked symbols. Errors if not found", "dlopen", "1 handle (not GC'd)", "O(1)", 34 },
	{ "ffi-variadic", "( lib symbol arg-types ret-type n-fixed -- ) <name>", "Like ffi-function for a variadic C function: n-fixed leading arguments use the fixed convention, the rest the variadic one (ffi_prep_cif_var). Variadic argument types are fixed per binding, so declare one word per type combination (e.g. a :string setopt and a :long setopt)", "dlsym + prep_cif_var", "1 binding", "O(argc)", 34 },
	{ "fgt", "( a b -- f ) ⚠", "float gt, result 1.0/0.0; no type check", "2", "none", "O(1)", 1 },
	{ "filter", "( arr/set xt -- arr )", "Keep elements where xt is truthy", "2 + n·xt", "malloc(n) flags + 1a(k)", "O(n·xt)", 23 },
	{ "find", "( items pred -- element )", "arrays.h2o: the first element for which pred is truthy, or the none value; stops at the first hit", "n·xt", "none", "O(n·xt)", 23 },
	{ "five-number-summary", "( v -- fr )", "statistics.h2o: { :min :q1 :median :q3 :max } over a vector's finite elements (NaNs dropped)", "4n log n", "malloc(n) ×4 + 1fr", "O(n log n)", 18 },
	{ "flat-map", "( items xt -- arr )", "arrays.h2o: map flatten-array; xt returns an array per element, results concatenated", "n·xt + total", "1a(n) + 1a(total)", "O(n·xt + total)", 23 },
	{ "flatten", "( m -- m' )", "matrix.h2o: 1×(r·c) reshape", "r×c", "1m(1×r·c)", "O(r×c)", 18 },
	{ "flatten-array", "( arr -- arr )", "Flatten one level; returns the input unchanged if no element is itself an array", "1 + m", "1a(m)", "O(m)", 14 },
	{ "fln", "( a -- ln a ) ⚠", "natural log, in place", "1", "none", "O(1)", 1 },
	{ "float?", "( a -- bool )", "core.h2o: type-of :float = (inlined)", "5", "none", "O(1)", 4 },
	{ "flog", "( a -- log₁₀ a ) ⚠", "base-10 log, in place", "1", "none", "O(1)", 1 },
	{ "flt", "( a b -- f ) ⚠", "float lt, result 1.0/0.0; no type check", "2", "none", "O(1)", 1 },
	{ "fmod", "( a b -- fmod(a,b) ) ⚠", "fmod", "2", "none", "O(1)", 1 },
	{ "fnegate", "( a -- -a ) ⚠", "in place", "1", "none", "O(1)", 1 },
	{ "forget", "—", "Read the following name; truncate the dictionary back to before it", NULL, NULL, NULL, 10 },
	{ "format", "( … template -- s )", "Fill template's {n} (or {n:spec}) placeholders with the nth-from-top stack value, then drop exactly the referenced positions (unreferenced values stay); renders floats/strings/symbols. {nl} and {tab} emit a newline and a tab — string literals have no escapes, so format is where control characters come from. Only these directives substitute; other brace content is left literal", "len + refs", "1o", "O(len)", 12 },
	{ "format-time", "( instant format -- string )", "Render with strftime, UTC", "len", "1s", "O(len)", 21 },
	{ "format-time-local", "( instant format -- string )", "Render with strftime in the process's timezone", "len", "1s", "O(len)", 21 },
	{ "frame", "( keys values -- fr )", "Build from parallel key and value arrays of equal length", "2 + n log n", "1o + reallocs", "O(n log n)", 16 },
	{ "frame>array", "( fr -- arr )", "Flatten to a key-sorted alternating-kv array; inverse of array>frame", "1 + n", "1o", "O(n)", 16 },
	{ "frame>json", "( val -- s )", "Serialize a value to JSON. Floats use the shortest round-trip form; strings are escaped (non-ASCII emitted raw); object keys are the symbol names", "walk + build", "1o string", "O(tree size)", 17 },
	{ "frame?", "( a -- bool )", "core.h2o: type-of :frame = (inlined)", "5", "none", "O(1)", 4 },
	{ "frobenius-norm", "( m -- f )", "√(Σ aᵢⱼ²) over all elements (same value as norm)", "1 + n", "none", "O(n)", 18 },
	{ "fround", "( a -- round a ) ⚠", "nearest, in place", "1", "none", "O(1)", 1 },
	{ "fround-down", "( a -- floor a ) ⚠", "in place", "1", "none", "O(1)", 1 },
	{ "fround-up", "( a -- ceil a ) ⚠", "in place", "1", "none", "O(1)", 1 },
	{ "fsin", "( a -- sin a ) ⚠", "sine (radians), in place", "1", "none", "O(1)", 1 },
	{ "fsq", "( a -- a² ) ⚠", "in place", "1", "none", "O(1)", 1 },
	{ "fsqrt", "( a -- √a ) ⚠", "in place", "1", "none", "O(1)", 1 },
	{ "ftan", "( a -- tan a ) ⚠", "tangent (radians), in place", "1", "none", "O(1)", 1 },
	{ "ftanh", "( a -- tanh a ) ⚠", "hyperbolic tangent, in place", "1", "none", "O(1)", 1 },
	{ "ftruncate", "( a -- trunc a ) ⚠", "toward zero, in place", "1", "none", "O(1)", 1 },
	{ "gc", "( -- )", "Force a mark-sweep now", "walks stacks + dict + roots, frees unmarked", "none", "O(objects + dict)", 29 },
	{ "gen-each", "( producer consumer -- )", "generators.h2o: run consumer on each value the producer yields until the producer falls off (a :gen-end sentinel marks exhaustion)", "—", "cont/step", "O(values · consumer)", 25 },
	{ "gen-take", "( producer count -- array )", "generators.h2o: the first count values the producer yields, collected into an array", "—", "1a(count) + cont/step", "O(count · L)", 25 },
	{ "group-by", "( array col -- frame )", "Group an array of frames by their symbol-valued col into a frame from each value to a set of the matching rows; one sorted pass, distinct values sorted", "n log n", "frame + sets", "O(n log n)", 13 },
	{ "group-with", "( items xt -- fr )", "arrays.h2o: group elements into { key → set } by the symbol key xt ( element -- sym ) computes — the quotation-keyed kin of group-by", "n·(xt + log n)", "frame + sets", "O(n·xt + n log n)", 23 },
	{ "gt", "( a b -- bool ) or ( m x -- m )", "greater-than; element-wise 1/0 matrix on matrix operands (scalar broadcast)", "3 (float)", "matrix 1m(r×c)", "same; matrix O(r×c)", 4 },
	{ "has?", "( fr sym/path -- bool )", "Existence test for a frame key or path, no error on miss; a search path is true if any node matches (short-circuits at the first); on a string ( s pat -- bool ), true if regex pat matches anywhere", "3 + d log n", "none", "O(d log n)", 16 },
	{ "head-tail", "( pair -- head tail )", "Split a pair — head under, tail on top; no auto-deref; errors on a non-pair", "1", "none", "O(1)", 15 },
	{ "help", "( \"name\" -- )", "core.h2o: parse the next word and print its man frame (lookup man .)", "dict scan + log n", "1o + strings + print", "O(|dict|)", 29 },
	{ "histogram-table", "( v n-bins -- fr )", "statistics.h2o: equal-width bin counts over a vector's value range, as { :counts (n-bins×1) :low :bin-width }. NaNs dropped, the top value lands in the last bin, a constant vector takes the range value ± 1; errors on n-bins < 1 or no finite values", "n + n-bins", "1m(n-bins) + 1fr", "O(n + n-bins)", 18 },
	{ "hstack", "( a b -- m )", "matrix.h2o: augment under its numpy name (inlined)", "2 + r·c", "1m(r×c)", "O(r·c)", 18 },
	{ "i-times", "( xt n -- )", "Run xt n times, pushing index 0..n-1 first", "2 + n·(1+xt)", "none", "O(n·xt)", 23 },
	{ "identity-matrix", "( n -- m )", "matrix.h2o: 1 swap diagonal-matrix", "n", "1m(n×n)", "O(n)", 18 },
	{ "if", "( flag -- )", "Branch past the then/else if flag is falsy", NULL, NULL, NULL, 8 },
	{ "index-of", "( s pat -- i )", "strings.h2o: codepoint index of pat's first regex match in s, or -1 if none (split 0 @i size guarded by has?)", "n", "1a + pieces", "O(n)", 12 },
	{ "inline", "—", "Mark the most recent definition inline; future calls splice its body", NULL, NULL, NULL, 10 },
	{ "inner-join", "( driver probed col -- [rows] )", "Inner join: each driver row merged (probed columns win collisions) with each probed row sharing col's value; probed must index col", "—", "1a", "O(driver·log probed)", 27 },
	{ "int-segment", "( n -- seg )", "n-element int segment, zero-filled; errors if n < 0", "1", "1seg(n)", "O(n)", 19 },
	{ "internal", "—", "Mark the most recent definition internal: hidden from words, apropos, and completion (still findable by name and tick)", NULL, NULL, NULL, 10 },
	{ "intersection", "( s₁ s₂ -- s₃ )", "Intersection into a new set, merging the two sorted arrays", "m+n", "1o + reallocs", "O(m+n)", 13 },
	{ "iota", "( n -- arr )", "arrays.h2o: [0…n−1], empty when n ≤ 0", "3 + n", "1a(n)", "O(n)", 14 },
	{ "iqr", "( m -- f )", "statistics.h2o: interquartile range, Q3 − Q1", "2n log n", "malloc(n) ×2", "O(n log n)", 18 },
	{ "iso>time", "( string -- instant )", "units.h2o: parse the Z form time>iso emits", "len", "1 pair", "O(1)", 21 },
	{ "join", "( arr sep -- s )", "Concatenate the string elements of arr separated by sep; errors on a non-string element", "2 + total", "1o", "O(total)", 12 },
	{ "json>frame", "( s -- val )", "Parse a JSON string. Escapes and \\uXXXX (with surrogate pairs) decode to UTF-8; recursive-descent, depth-guarded; rejects trailing non-whitespace. Each object's keys are sorted after collection", "scan + build", "one object per node", "O(|s| log |s|)", 17 },
	{ "keys", "( fr -- arr )", "Keys (symbols) in sorted order", "1 + n", "1a(n)", "O(n)", 16 },
	{ "last", "( arr n -- arr )", "arrays.h2o: swap reverse swap take reverse", "3n", "3×1a(n)", "O(n)", 14 },
	{ "leave", "—", "Branch past the innermost loop's closing word; conditional form is if leave then", NULL, NULL, NULL, 8 },
	{ "ln", "( a -- ln a )", "log — natural log", "2", "matrix 1m(r×c)", "same", 3 },
	{ "load", "( s -- )", "Run a source file as if typed; record it for reload", "file read + run", "input buffer", "O(file)", 30 },
	{ "load-bag", "( rel rows-array -- rel )", "Like bulk-load, but :rows stays a **bag** (the array, duplicates kept) rather than a deduped set; only :index is built", "n", "frame + sets", "O(n)", 27 },
	{ "load-image", "( s -- )", "Restore a binary snapshot, replacing current state", "deserialize all", "reallocates all objects", "O(objects)", 30 },
	{ "log", "( a -- log₁₀ a )", "log10", "2", "matrix 1m(r×c)", "same", 3 },
	{ "lookup", "( \"name\" -- xt )", "Parse the following word at run time and push its xt — the non-immediate counterpart of '", NULL, NULL, NULL, 10 },
	{ "lowest-bit", "( a -- i )", "0-indexed position of the lowest set bit (-1 if a is 0)", "1", "none", "O(1)", 4 },
	{ "lshift", "( a n -- f )", "left shift a by n bits", "2", "none", "O(1)", 4 },
	{ "lt", "( a b -- bool ) or ( m x -- m )", "less-than; element-wise 1/0 matrix on matrix operands (scalar broadcast)", "3 (float)", "matrix 1m(r×c)", "same; matrix O(r×c)", 4 },
	{ "lvar", "( -- v )", "Push a fresh, unbound logic variable", "2", "1 lvar", "O(1)", 26 },
	{ "lvar?", "( a -- bool )", "core.h2o: type-of :lvar = (inlined)", "5", "none", "O(1)", 4 },
	{ "magnitude", "( v -- v' )", "A quantity's bare magnitude (float or matrix, the unit dropped); any other value passes through unchanged", "2", "none", "O(1)", 5 },
	{ "man", "( xt -- fr )", "Frame of a word's reference entry (:word :effect :summary, plus :ops :alloc :order for runtime words); a unit word synthesizes its entry from the unit's definition (unit: m × 1000); T_NONE if undocumented", "dict scan + log n", "1o + strings", "O(|dict|)", 29 },
	{ "map", "( arr/set xt -- arr )", "Apply xt to each element; xt must net exactly one value", "2 + n·xt", "1a(n)", "O(n·xt)", 23 },
	{ "mapn", "( arr₁ … arr_N xt N -- arr )", "N-ary zip-map over equal-length arrays", "rows·(N+xt)", "1a(rows)", "O(rows·xt)", 23 },
	{ "match", "( s pat -- [ whole cap… ] | 0 )", "First (leftmost) match as a flat array: whole match then each capture; no match returns 0", "n", "1a + captures", "O(n)", 12 },
	{ "match-all", "( s pat -- [ [whole cap…] … ] | 0 )", "Every non-overlapping leftmost match, each a flat sub-array; a zero-width match advances one byte; no match returns 0", "n", "1a per match + captures", "O(n + m·g)", 12 },
	{ "matches?", "( a b -- flag )", "Non-destructive unify test: mark the trail, unify a and b, roll the trail back, push whether they unified. Leaves no bindings and never backtracks (so it composes in straight-line code, unlike unify)", "n", "none", "O(n)", 26 },
	{ "matrix", "( arr r c -- m ) or ( arr r -- m )", "Build from a float array; two-arg form takes r = rows and infers columns", "3 + r×c", "1m(r×c)", "O(r×c)", 18 },
	{ "matrix-range", "( start end step -- m )", "1×N row of evenly spaced values", "3 + N", "1m(1×N)", "O(N)", 18 },
	{ "matrix>pointer", "( m -- ptr )", "Intern the matrix's row-major element buffer and return a T_PTR handle to pass as a :ptr argument; no copy — aliases the live buffer (amortized intern)", "1", "none", "O(1)", 34 },
	{ "matrix?", "( a -- bool )", "core.h2o: type-of :matrix = (inlined)", "5", "none", "O(1)", 4 },
	{ "max", "( m -- f )", "Maximum element", "1 + r×c", "none", "O(r×c)", 18 },
	{ "max2", "( a b -- larger )", "core.h2o: the lt-ordered greater of two scalars, min2's twin", "5", "none", "O(1)", 1 },
	{ "mean", "( m -- f )", "matrix.h2o: sum ÷ element count", "r×c", "none", "O(r×c)", 18 },
	{ "median", "( m -- f )", "statistics.h2o: 0.5 quantile (inlined)", "n log n", "malloc(n)", "O(n log n)", 18 },
	{ "member?", "( set v -- bool )", "Binary-search membership", "3 + log n", "none", "O(log n)", 13 },
	{ "merge", "( fr₁ fr₂ -- fr )", "New frame with all keys; fr₂ wins collisions. A linear two-pointer merge of the two sorted key arrays", "m+n", "1o", "O(m+n)", 16 },
	{ "min", "( m -- f )", "Minimum element", "1 + r×c", "none", "O(r×c)", 18 },
	{ "min2", "( a b -- smaller )", "core.h2o: the lt-ordered lesser of two scalars (2dup gt if swap then drop, inlined); min/max reduce a matrix, these order a pair", "5", "none", "O(1)", 1 },
	{ "mod", "( a b -- remainder )", "core.h2o: % drop; sign follows dividend", "5", "none", "O(1)", 3 },
	{ "nan?", "( v -- bool ) or ( m -- m )", "NaN test: 1/0 mask over a matrix's elements; 1 on null itself (a scalar NaN *is* null), 0 on any float. The only mask route to NaNs — they compare false under lt/gt/eq", "2", "matrix 1m(r×c)", "O(1); matrix O(r×c)", 4 },
	{ "negate", "( a -- -a )", "float or matrix (element-wise)", "2 (float)", "matrix 1m(r×c)", "float O(1); matrix O(r×c)", 1 },
	{ "nip", "( a b -- b )", "core.h2o: swap drop (inlined)", "5", "none", "O(1)", 0 },
	{ "none?", "( a -- bool )", "core.h2o: type-of :none = (inlined)", "5", "none", "O(1)", 4 },
	{ "nonmissing-count", "( m -- n )", "The number of non-NaN elements — the divisor mean and se use", "1 + n", "none", "O(n)", 18 },
	{ "norm", "( m -- f )", "Euclidean (L2) norm: √(Σ aᵢⱼ²) over all elements — a vector's length; for a matrix the Frobenius (entrywise 2-)norm, not the spectral norm", "1 + n", "none", "O(n)", 18 },
	{ "not", "( a -- bool )", "logical not of truthiness", "2", "none", "O(1)", 4 },
	{ "now", "( -- f )", "CLOCK_MONOTONIC seconds as a float", "1", "none", "O(1)", 29 },
	{ "null", "( -- none )", "Push the none value (T_NONE) — what JSON null parses to, and what an unset env returns", "1", "none", "O(1)", 17 },
	{ "num-cores", "( -- n )", "Online CPU count (sysconf)", "1", "none", "O(1)", 23 },
	{ "num-elements", "( m -- n )", "matrix.h2o: dim * (inlined)", "5", "none", "O(1)", 18 },
	{ "or", "( a b -- bool )", "logical or of truthiness", "3", "none", "O(1)", 4 },
	{ "over", "( a b -- a b a )", "Copy second over top", "5", "none", "O(1)", 0 },
	{ "pair?", "( a -- bool )", "core.h2o: type-of :pair = (inlined)", "5", "none", "O(1)", 4 },
	{ "parallel-run", "( commands width -- results )", "subprocess.h2o: run each argv array in commands as a subprocess, at most width at once; collect { :out :err :status } per command in input order, refilling a slot as each child finishes", "fork per command + poll", "1a + per-child frames/streams", "O(critical path)", 32 },
	{ "parse-time", "( string format -- instant )", "Parse with strptime; uncaptured fields default to 1970-01-01 00:00:00, read as UTC unless the format captures an offset with %z; errors on a mismatch", "len", "1 pair", "O(len)", 21 },
	{ "partition", "( items pred -- matches rest )", "arrays.h2o: the elements satisfying pred and the others, one pass, input order kept", "n·xt", "2 arrays", "O(n·xt)", 23 },
	{ "pbootstrap", "( data fit-xt B -- arr )", "statistics.h2o: bootstrap with the fits run under pmap — identical results (per-replicate seeding), parallel resample+fit", "as bootstrap", "as bootstrap", "O(B·(n + fit) / cores)", 18 },
	{ "percentile", "( m pct -- f )", "statistics.h2o: quantile at pct ∈ [0,100] (inlined)", "n log n", "malloc(n)", "O(n log n)", 18 },
	{ "pfilter", "( arr pred -- arr )", "Parallel filter, order preserved", "2 + n·xt", "malloc(n) flags + 1a(k)", "O(n·xt / w)", 23 },
	{ "pfilter-ext", "( arr w c pred -- arr )", "pfilter with explicit worker count and items-per-claim", "2 + n·xt", "malloc(n) flags + 1a(k)", "O(n·xt / w)", 23 },
	{ "pi", "( -- f )", "core.h2o: variable initialized to π (3.141592653589793); invoking it pushes the stored float", "1", "none", "O(1)", 1 },
	{ "pmap", "( arr xt -- arr )", "Parallel map (num-cores workers, claim 1)", "2 + n·xt", "1a(n)", "O(n·xt / w)", 23 },
	{ "pmap-ext", "( arr w c xt -- arr )", "pmap with explicit worker count and items-per-claim", "2 + n·xt", "1a(n)", "O(n·xt / w)", 23 },
	{ "pmap-reduce", "( arr id map-xt combine-xt -- val )", "Fused parallel map+fold; combine-xt must be associative with id as neutral element", "2 + n·xt", "per-worker partials", "O(n·xt / w)", 23 },
	{ "pmap-reduce-ext", "( arr w c id map-xt combine-xt -- val )", "pmap-reduce with explicit worker count and items-per-claim", "2 + n·xt", "per-worker partials", "O(n·xt / w)", 23 },
	{ "print", "( x -- )", "core.h2o: alias for .", "1 + print", "none", "O(size printed)", 11 },
	{ "print-stack", "( -- )", "core.h2o: alias for .s", "print", "none", "O(depth)", 11 },
	{ "ptr?", "( a -- bool )", "core.h2o: type-of :ptr = (inlined)", "5", "none", "O(1)", 4 },
	{ "qnorm", "( p -- z )", "statistics.h2o: standard normal quantile (inverse CDF), Acklam's rational approximation — relative error below 1.15e-9, matching R's qnorm to 1e-8 over both tails; errors unless p strictly inside (0, 1)", "30", "none", "O(1)", 18 },
	{ "quantile", "( m p -- f )", "Linearly-interpolated quantile at p ∈ [0,1] over all elements (sorts a copy); errors if p out of range or empty", "2 + n log n", "malloc(n)", "O(n log n)", 18 },
	{ "quantity?", "( a -- bool )", "core.h2o: type-of :quantity = (inlined)", "5", "none", "O(1)", 4 },
	{ "query", "( rel pattern -- [rows] )", "Array of rows matching pattern; uses an index when the pattern grounds an indexed column, else scans. When every constraint is a ground indexed column the narrowed bucket *is* the answer, so the per-row matches? is skipped (covering query)", "candidates·n", "1a + set ops", "O(candidates·n)", 27 },
	{ "quotient", "( a b -- quotient )", "core.h2o: % swap drop; toward zero", "9", "none", "O(1)", 3 },
	{ "r>", "return stack → ( -- a )", "Move return-stack top to data stack", "2", "none", "O(1)", 6 },
	{ "r@", "( -- a )", "Copy return-stack top to data stack", "2", "none", "O(1)", 6 },
	{ "random", "( -- f )", "Uniform float in [0,1)", "1", "none", "O(1)", 20 },
	{ "random-int", "( bound -- f )", "Uniform integer in [0,bound) as a float, by rejection sampling; errors if bound ≤ 0", "1", "none", "O(1)†", 20 },
	{ "range", "( from to -- arr )", "Inclusive integer range, step ±1", "3 + n", "1a(n)", "O(n)", 14 },
	{ "ranks", "( v -- v' )", "statistics.h2o: 0-based ordinal ranks as nx1, as-column argsort argsort (inlined); ties ranked in index order, not midranked", "2n log n", "2m(n) + malloc(16n) ×2", "O(n log n)", 18 },
	{ "read", "( stream -- s )", "Read the stream to EOF into one string", "read syscalls", "1o + buffer growth", "O(bytes)", 32 },
	{ "read-err", "( proc -- s )", "subprocess.h2o: read the child's :err stream to EOF", "read syscalls", "1o + buffer growth", "O(bytes)", 32 },
	{ "read-file", "( path -- s )", "Read a whole file as one string (byte-safe); errors if it can't be opened", "file read", "1o + buffer", "O(file)", 31 },
	{ "read-out", "( proc -- s )", "subprocess.h2o: read the child's :out stream to EOF", "read syscalls", "1o + buffer growth", "O(bytes)", 32 },
	{ "read-tsv", "( path -- rows )", "Read a TSV file into an array of row-arrays; an empty cell → none, a numeric cell → float, else a string. No header handling", "1 + bytes", "1a(r) + one array per row + a string per text cell", "O(bytes)", 22 },
	{ "reduce", "( arr/set init xt -- val )", "Left fold; xt is ( acc elem -- acc )", "3 + n·xt", "none", "O(n·xt)", 23 },
	{ "regress-with", "( dataset predictors response B fit-xt -- arr )", "statistics.h2o: the shared regression pipeline — design matrix with intercept, point estimate, then B bootstrap refits for per-coefficient { :estimate :se :bias :ci-low :ci-high } frames; the loadable statistics library's linear-regression/logistic-regression pass the fit", "fit + B·fit", "matrices + B refits + 1a(k)", "O(B·fit)", 18 },
	{ "reify", "( a -- a' )", "Like copy, but each unbound var becomes a canonical inert symbol :_0, :_1, … numbered by first appearance — a ground, storable, comparable snapshot.", "tree size", "one object per node", "O(tree size)", 16 },
	{ "relation", "( [cols] -- rel )", "New empty relation; cols is an array of column symbols to index", "k", "frames + sets", "O(k)", 27 },
	{ "reload", "( -- )", "Truncate user state, re-run every loaded file in order", "forget + N loads", "—", "O(Σ files)", 30 },
	{ "remove-last!", "( arr -- v )", "Remove and return the last element; errors on an empty array", "2", "none", "O(1)", 14 },
	{ "render", "( a -- s )", "The text . would print, returned as a string instead of printed: no truncation, no trailing separator (a matrix grid's final newline is dropped). Strings render raw, symbols by name, collections/frames/matrices in their laid-out form", "1 + size", "1o", "O(size)", 11 },
	{ "repeat", "—", "Branch back to begin; patches the while exit", NULL, NULL, NULL, 8 },
	{ "replace", "( s pat rep -- s' )", "Replace **all** matches; in rep, & or \\0 is the whole match, \\1–\\9 a capture, \\& and \\\\ literals", "n", "1o + buffer growth", "O(n)", 12 },
	{ "resample-indices", "( n -- arr )", "datasets.h2o: n indices drawn from [0,n) with replacement (bootstrap), from the global stream", "2n", "2×1a(n)", "O(n)", 22 },
	{ "resample-indices-ext", "( n seed -- arr )", "n indices drawn from [0,n) with replacement by a private generator seeded from seed (splitmix64-expanded) — same draw for the same seed regardless of thread or stream position; the bootstrap words seed replicate i at run-seed + i", "n", "1a(n)", "O(n)†", 22 },
	{ "reset", "( -- )", "Push a unique mark on the return stack, delimiting the captured region", "1", "none", "O(1)", 24 },
	{ "reshape", "( m r c -- m' )", "Same elements, new shape (must match); memcpy", "3 + r×c", "1m(r×c)", "O(r×c)", 18 },
	{ "resume", "( k -- … )", "Pop k and re-enter it (multi-shot — the continuation object survives, so a retained copy can be resumed again); pushes whatever the resumed code yields", "L + resumed", "none", "O(L + resumed)", 24 },
	{ "retract", "( rel pattern -- rel )", "Remove every row matching pattern from :rows and all buckets. Mutates rel, returns it", "matches·(k+n)", "1a", "O(matches·n)", 27 },
	{ "reverse", "( arr/set -- arr )", "Reversed copy", "1 + n", "1a(n)", "O(n)", 14 },
	{ "roll", "( xₙ … x₀ n -- xₙ₋₁ … x₀ xₙ )", "Move the item n deep to the top; memmoves the n above it down", "2 + n", "none", "O(n)", 0 },
	{ "rot", "( a b c -- b c a )", "Rotate top three", "6", "none", "O(1)", 0 },
	{ "round", "( a -- round a )", "round", "2", "matrix 1m(r×c)", "same", 3 },
	{ "round-down", "( a -- floor a )", "floor", "2", "matrix 1m(r×c)", "same", 3 },
	{ "round-up", "( a -- ceil a )", "ceil", "2", "matrix 1m(r×c)", "same", 3 },
	{ "row-maxes", "( m -- m' )", "r×1 of per-row maxima", "1 + r×c", "1m(r×1)", "O(r×c)", 18 },
	{ "row-means", "( m -- m' )", "matrix.h2o: row-sums then scalar ÷", "r×c", "2×1m(r×1)", "O(r×c)", 18 },
	{ "row-mins", "( m -- m' )", "r×1 of per-row minima", "1 + r×c", "1m(r×1)", "O(r×c)", 18 },
	{ "row-sums", "( m -- m' )", "r×1 of per-row sums", "1 + r×c", "1m(r×1)", "O(r×c)", 18 },
	{ "rows>dataset", "( table header? -- dataset )", "datasets.h2o: column-oriented frame from a table; keys come from row 0 when header? is true, else :col1… are synthesized", "r·c", "k×1a(r) + 1fr", "O(r·c)", 22 },
	{ "rows>relation", "( table index-cols header? -- relation )", "datasets.h2o: deduped relation indexed on index-cols (coerced to symbols)", "r·c", "one frame per row + relation + index buckets", "O(r·c)", 22 },
	{ "rshift", "( a n -- f )", "arithmetic right shift, = floor(a / 2ⁿ)", "2", "none", "O(1)", 4 },
	{ "run", "( s -- proc )", "subprocess.h2o: split a command string on runs of spaces and start-process it (\" +\" split start-process)", "split + fork", "1a + 1o frame + 3 streams", "O(|s| + argc)", 32 },
	{ "run-result", "( argv -- frame )", "subprocess.h2o: run argv to completion and return { :out :err :status }, closing the streams and reaping the child", "fork + drain", "1fr + output strings", "O(output)", 32 },
	{ "running?", "( pid -- bool )", "Non-blocking liveness via waitid+WNOHANG+WNOWAIT; true while running, false once exited. Non-reaping, so a later wait still returns the status", "1 syscall", "none", "O(1)", 32 },
	{ "sample", "( arr/set count repl -- arr )", "Draw count elements; repl truthy = with replacement, else without (count ≤ len)", "3 + n", "1a(count) (+ malloc(n) without replacement)", "O(n)", 14 },
	{ "sample-with-replacement", "( arr n -- arr )", "statistics.h2o: true sample (inlined)", "n", "as sample", "O(n)", 18 },
	{ "sample-without-replacement", "( arr n -- arr )", "statistics.h2o: false sample (inlined)", "n", "as sample", "O(n)", 18 },
	{ "save", "( s -- )", "Write all user words as re-loadable .h2o source", "dict scan + write", "file I/O", "O(|user dict|)", 30 },
	{ "save-image", "( s -- )", "Binary snapshot of full state (dict, objects, stacks, continuations)", "serialize all", "file I/O", "O(objects + dict)", 30 },
	{ "se", "( m -- f )", "statistics.h2o: standard error of the mean, std / sqrt(n)", "n", "none", "O(n)", 18 },
	{ "see", "( xt -- )", "Print a word's source (: name … ;), or variable/symbol/primitive form", "dict scan", "none", "O(|dict|)", 29 },
	{ "see-compiled", "( xt -- )", "Disassemble a colon definition's compiled cells", "body scan", "none", "O(body)", 29 },
	{ "see-compiled>string", "( xt -- s )", "The text see-compiled would print, returned as a string (trailing newline stripped)", "body scan", "1o", "O(body)", 29 },
	{ "see-tree", "( xt -- )", "Like see-compiled, but each colon-word call is expanded inline, indented two spaces, recursively down to primitives; recursive calls print as name ...", "body scan", "none", "O(expanded body)", 29 },
	{ "see-tree>string", "( xt -- s )", "The text see-tree would print, returned as a string (trailing newline stripped)", "body scan", "1o", "O(expanded body)", 29 },
	{ "see>string", "( xt -- s )", "The text see would print, returned as a string (trailing newline stripped)", "dict scan", "1o", "O(|dict|)", 29 },
	{ "seed", "( n -- )", "Set the global base seed and reset the stream counter; per-thread streams derive from it", "1", "none", "O(1)", 20 },
	{ "segment>pointer", "( seg -- ptr )", "Intern the backing buffer and return an FFI pointer handle (no copy; see Foreign function interface)", "1", "none", "O(1)†", 19 },
	{ "segment?", "( a -- bool )", "core.h2o: type-of :segment = (inlined)", "5", "none", "O(1)", 4 },
	{ "select-keys", "( fr path -- arr )", "The full root-to-match path (a symbol array) for every match, document order; each round-trips through @", "s", "1a + 1a per match", "O(s + total path length)", 16 },
	{ "select-rows", "( m idx -- m )", "New matrix of the rows named by idx — a float index array or an index vector (nx1 or 1xn, as where/argsort return); errors on a non-float or out-of-range index", "2 + k·c", "1m(k×c)", "O(k·c)", 18 },
	{ "select-values", "( fr path -- arr )", "Every matched value, in document (pre-order) order, duplicates kept; no path built per match", "s", "1a + reallocs", "O(s)", 16 },
	{ "set", "( v₀ … vₙ₋₁ n -- set )", "Gather the top n values into a new set (the set analog of array)", "2 + n log n", "1o + reallocs", "O(n log n)", 13 },
	{ "set-add!", "( set v -- set )", "Insert v in sorted position if absent (dedups); leaves set on the stack", "log n + n", "reallocs", "O(n)", 13 },
	{ "set-remove!", "( set v -- set )", "Remove v if present (no-op if absent); leaves set on the stack", "log n + n", "none", "O(n)", 13 },
	{ "set?", "( a -- bool )", "core.h2o: type-of :set = (inlined)", "5", "none", "O(1)", 4 },
	{ "shift", "( -- k )", "Capture the return-stack slice up to the nearest reset, remove the mark and that slice, push k", "L", "1o (cont)", "O(L)", 24 },
	{ "shift-with", "( xt -- )", "Capture as shift, then run xt in the outer context with k on the stack and begin unwinding", "L + xt", "1o (cont)", "O(L + xt)", 24 },
	{ "shuffle", "( arr -- arr )", "datasets.h2o: new array, elements uniformly permuted (a full sample without replacement); input untouched", "3 + n", "as sample", "O(n)", 14 },
	{ "side-depth", "( -- n )", "Push side-stack depth", "1", "none", "O(1)", 7 },
	{ "side-drop", "( -- )", "Discard side-stack top", "1", "none", "O(1)", 7 },
	{ "side>", "( -- a )", "Pop from side stack", "2", "none", "O(1)", 7 },
	{ "sigmoid", "( m -- m' )", "statistics.h2o: elementwise logistic 1/(1+e⁻ˣ), mapping reals to (0,1)", "4n", "1m(r×c)", "O(n)", 18 },
	{ "sin", "( a -- sin a )", "sine (radians)", "2", "matrix 1m(r×c)", "same", 3 },
	{ "size", "( coll -- n )", "Element count: set/array members, **codepoints** of a string, pair count of a frame; a string's codepoint count is computed on first use and memoized on the object", "2", "none", "O(1); a string's first size is O(n)", 13 },
	{ "skip", "( arr n -- arr )", "arrays.h2o: over size swap - swap reverse swap take reverse", "3n", "3×1a(n)", "O(n)", 14 },
	{ "sleep", "( seconds -- )", "Block for the given float seconds (sub-second supported); nanosleep", "blocks", "none", "O(1)", 29 },
	{ "slice!", "( arr tstart src sstart sstep slen -- arr )", "Copy slen elements src[sstart], src[sstart+sstep], … into arr[tstart…] in place", "6 + slen", "self-overlap may malloc slen", "O(slen)", 14 },
	{ "sort", "( arr/set/v -- arr/v )", "Sorted copy: an array orders by val_cmp; a set projects its already-ordered elements to an array; an nx1 or 1xn vector sorts ascending with NaNs last (other matrix shapes error)", "1 + n log n", "1a(n) / 1m(n)", "O(n log n); vectors above 8k elements O(n) radix", 14 },
	{ "sort-by", "( items xt -- arr )", "arrays.h2o: sorted by the key xt ( element -- key ) extracts — decorate-sort-undecorate over [ key element ] pairs, so n key evaluations", "n·xt + n log n", "3×1a(n) + n×1a(2)", "O(n·xt + n log n)", 23 },
	{ "split", "( s pat -- [ piece… ] )", "Split s at each non-overlapping match of pat; the pieces are the gaps between matches, empty fields kept; no match → [ s ]", "n", "1a + pieces", "O(n)", 12 },
	{ "sq", "( a -- a² )", "float or matrix", "2 (float)", "matrix 1m(r×c)", "float O(1); matrix O(r×c)", 1 },
	{ "sqrt", "( a -- √a )", "sqrt", "2", "matrix 1m(r×c)", "same", 3 },
	{ "start-generator", "( producer -- value generator )", "generators.h2o: reset execute — run producer to its first yield; leaves the yielded value and a resumable continuation", "L", "1o (cont)", "O(producer to first yield)", 25 },
	{ "start-process", "( argv -- proc )", "fork/exec argv[0] with argv as its arguments; return { :pid :in :out :err } (the three streams are T_STREAM)", "fork + 3 pipes", "1o frame + 3 streams", "O(argc)", 32 },
	{ "std", "( m -- f )", "statistics.h2o: standard deviation, var sqrt (inlined)", "n", "none", "O(n)", 18 },
	{ "stderr", "( -- stream )", "Standard error as a T_STREAM over fd 2; composes with write/close like any stream", "1", "none", "O(1)", 32 },
	{ "stdin", "( -- stream )", "Standard input as a T_STREAM over fd 0; stdin read slurps it. (Conflicts with the REPL reading its own program from stdin — for file-loaded programs.)", "1", "none", "O(1)", 32 },
	{ "stdout", "( -- stream )", "Standard output as a T_STREAM over fd 1; s stdout write emits", "1", "none", "O(1)", 32 },
	{ "stop", "( pid -- status )", "SIGKILL the child then reap it (137 = 128+9, or its code if it had already exited)", "2 syscalls", "none", "O(1)", 32 },
	{ "stream?", "( a -- bool )", "core.h2o: type-of :stream = (inlined)", "5", "none", "O(1)", 4 },
	{ "string>chars", "( s -- [ char… ] )", "Array of one-character strings, one per codepoint", "n", "1a + 1o/char", "O(n)", 12 },
	{ "string>codepoints", "( s -- [ code… ] )", "Array of integer codepoints, one per codepoint", "n", "1a", "O(n)", 12 },
	{ "string>number", "( s -- n | none )", "Parse a decimal/float string (via strtod, like a numeric literal) to a float, ignoring surrounding whitespace; the none value if s is not entirely a number", "n", "none", "O(n)", 12 },
	{ "string>symbol", "( s -- sym )", "Intern a computed string as a symbol", NULL, NULL, NULL, 10 },
	{ "string?", "( a -- bool )", "core.h2o: type-of :string = (inlined)", "5", "none", "O(1)", 4 },
	{ "submatrix", "( m rs re cs ce -- m )", "Copy the half-open block rows [rs,re) × cols [cs,ce); errors out of bounds or start > end", "5 + r·c", "1m(r×c)", "O(r·c)", 18 },
	{ "substring", "( s start end -- sub )", "Half-open **codepoint** range [start, end); bounds-checked against the codepoint count", "2 + n", "1o", "O(n)", 12 },
	{ "sum", "( m -- f )", "Sum of all elements (4-way unrolled, fast-math)", "1 + r×c", "none", "O(r×c)", 18 },
	{ "swap", "( a b -- b a )", "Exchange top two", "4", "none", "O(1)", 0 },
	{ "symbol", "—", "Read the following name; declare a word that pushes a specific interned symbol", NULL, NULL, NULL, 10 },
	{ "symbol?", "( a -- bool )", "core.h2o: type-of :symbol = (inlined)", "5", "none", "O(1)", 4 },
	{ "take", "( arr/set n -- arr )", "First n elements (clamped)", "2 + n", "1a(n)", "O(n)", 14 },
	{ "tan", "( a -- tan a )", "tangent (radians)", "2", "matrix 1m(r×c)", "same", 3 },
	{ "tanh", "( a -- tanh a )", "hyperbolic tangent", "2", "matrix 1m(r×c)", "same", 3 },
	{ "then", "—", "Close an if/if…else; patches the forward branch", NULL, NULL, NULL, 8 },
	{ "throw", "( exc -- )", "exceptions.h2o: [: drop 1 :] shift-with", "—", "1o (cont)", "O(stack depth)", 24 },
	{ "time>iso", "( instant -- string )", "units.h2o: \"%Y-%m-%dT%H:%M:%SZ\" format-time", "len", "1s", "O(1)", 21 },
	{ "times", "( xt n -- )", "Run xt n times, no index pushed", "2 + n·xt", "none", "O(n·xt)", 23 },
	{ "to", "( val -- )", "Assign to the named local (in a definition) or global. At the REPL, auto-creates the global if absent. In a definition, the variable must already exist. May trigger superword store-fusion while compiling.", NULL, NULL, NULL, 10 },
	{ "to-slice!", "( v₀ … vₙ₋₁ arr offset n -- arr )", "Store the n values just below arr into arr[offset…offset+n); leaves arr", "2 + n", "none", "O(n)", 14 },
	{ "transpose", "( m -- m' )", "Rows/columns swapped", "1 + r×c", "1m(c×r)", "O(r×c)", 18 },
	{ "trim", "( s -- s' )", "Strip leading and trailing ASCII whitespace (' ' \\t \\n \\v \\f \\r); a backward/forward byte-scan, one allocation of the surviving span", "n", "1o", "O(n)", 12 },
	{ "true", "( -- bool )", "core.h2o: pushes 1 (inline)", "1", "none", "O(1)", 4 },
	{ "truncate", "( a -- trunc a )", "trunc", "2", "matrix 1m(r×c)", "same", 3 },
	{ "try-catch", "( normal-xt err-xt -- … )", "exceptions.h2o: run normal-xt; on a throw or interpreter error, run err-xt with the exception (the { :message :trace } error frame, for an interpreter error) on the stack", "—", "cont if thrown; 1f + 2s on a caught interpreter error", "O(normal-xt)", 24 },
	{ "tsv>db", "( tsv-path db table -- info )", "database.h2o: import a TSV file into a new table. The header row names the columns (identifiers quoted, so any header text works); a column whose every non-empty cell is numeric is REAL, else TEXT; empty cells insert as NULL; all rows go in one transaction. info is { :n-rows N :columns [ … ] } — a :real column carries { :name :type :summary } with a five-number :summary, a :text column { :name :type :distinct } with COUNT(DISTINCT) (NULLs uncounted). Errors before creating anything on a missing or ragged file; an existing table errors on the CREATE, leaving it untouched", "r·c", "rows + dataset + 1s/statement", "O(r·c)", 33 },
	{ "type-of", "( a -- sym )", "The value's type as a symbol: :float :string :symbol :array :set :pair :frame :matrix :quantity :xt :continuation :stream :db :ptr :segment :none :wildcard :lvar. A bound logic var reports its value's type; an unbound one is :lvar", "2", "none", "O(1)", 4 },
	{ "unify", "( a b -- term )", "Unify a and b, binding logic vars (recorded on the trail) so the two match, then leave the dereffed left term. Atoms by value; pairs head then tail; arrays element-wise; frames as open records — shared keys must unify, extra keys on either side allowed. A _ on either side matches anything and binds nothing. On a mismatch, fails.", "n", "none", "O(n)", 26 },
	{ "union", "( s₁ s₂ -- s₃ )", "Union into a new set, merging the two sorted arrays", "m+n", "1o + reallocs", "O(m+n)", 13 },
	{ "unit", "( q -- )", "Read the following name; pop a quantity whose magnitude is a positive whole number, and define a postfix word attaching that unit. The magnitude is the unit's integer scale relative to its dimension's base (100 cent unit dollar). A single unnamed base dimension gets named after the word", NULL, NULL, NULL, 10 },
	{ "until", "( flag -- )", "Branch back to begin if flag is falsy", NULL, NULL, NULL, 8 },
	{ "update-at", "( fr sym/path xt -- fr )", "Apply xt to the value at the key, store the result back; errors on a search path", "d log n + xt", "none", "O(d log n + xt)", 16 },
	{ "values", "( fr -- arr )", "Values in key order", "1 + n", "1a(n)", "O(n)", 16 },
	{ "var", "( m -- f )", "Sample variance (÷ n−1) over all elements; errors with fewer than 2", "1 + n", "none", "O(n)", 18 },
	{ "variable", "—", "Read the following name; declare a global variable initialized to 0.0", NULL, NULL, NULL, 10 },
	{ "vector", "( arr -- v )", "matrix.h2o: the array as an nx1 matrix, length inferred (dup size 1 matrix, inlined)", "3 + n", "1m(n)", "O(n)", 18 },
	{ "vf*", "vf* a", "Multiply the stack top by variable a, in place", NULL, NULL, NULL, 28 },
	{ "vf+", "vf+ a", "Add variable a to the stack top, in place", NULL, NULL, NULL, 28 },
	{ "vf-", "vf- a", "Subtract variable a from the stack top, in place", NULL, NULL, NULL, 28 },
	{ "vf/", "vf/ a", "Divide the stack top by variable a, in place", NULL, NULL, NULL, 28 },
	{ "vfabs", "vfabs a", "Absolute value of variable a, push the result", NULL, NULL, NULL, 28 },
	{ "vfcos", "vfcos a", "cosine of variable a, push the result", NULL, NULL, NULL, 28 },
	{ "vfexp", "vfexp a", "eᵃ of variable a, push the result", NULL, NULL, NULL, 28 },
	{ "vflog", "vflog a", "base-10 log of variable a, push the result", NULL, NULL, NULL, 28 },
	{ "vfneg", "vfneg a", "Negate variable a, push the result", NULL, NULL, NULL, 28 },
	{ "vfsin", "vfsin a", "sine of variable a, push the result", NULL, NULL, NULL, 28 },
	{ "vfsq", "vfsq a", "Square variable a, push the result", NULL, NULL, NULL, 28 },
	{ "vfsqrt", "vfsqrt a", "Square root of variable a, push the result", NULL, NULL, NULL, 28 },
	{ "vftan", "vftan a", "tangent of variable a, push the result", NULL, NULL, NULL, 28 },
	{ "vftanh", "vftanh a", "hyperbolic tangent of variable a, push the result", NULL, NULL, NULL, 28 },
	{ "vstack", "( a b -- m )", "Stack two matrices row-wise (a on top of b); errors unless column counts match", "2 + r·c", "1m(r×c)", "O(r·c)", 18 },
	{ "vvf*", "vvf* a b", "Load variables a and b, multiply, push the result", NULL, NULL, NULL, 28 },
	{ "vvf*+", "vvf*+ b c", "( t -- t*b+c ), reading variables b and c", NULL, NULL, NULL, 28 },
	{ "vvf*-", "vvf*- b c", "( t -- c-t*b ), reading variables b and c", NULL, NULL, NULL, 28 },
	{ "vvf+", "vvf+ a b", "Load variables a and b, add, push the result", NULL, NULL, NULL, 28 },
	{ "vvf-", "vvf- a b", "Load variables a and b, subtract (a−b), push the result", NULL, NULL, NULL, 28 },
	{ "vvf/", "vvf/ a b", "Load variables a and b, divide (a/b), push the result", NULL, NULL, NULL, 28 },
	{ "wait", "( pid -- status )", "Block until the child exits; return its exit code, or 128 + signo if it was killed by a signal", "blocks", "none", "O(1)", 32 },
	{ "wall-now", "( -- instant )", "units.h2o: CLOCK_REALTIME epoch seconds as a quantity in s; steps when the system clock is adjusted, so time intervals with now", "1", "1 pair", "O(1)", 21 },
	{ "water", "( -- )", "Print the water logo and the interpreter version", "print", "none", "O(1)", 29 },
	{ "where", "( m -- v )", "Flat row-major indices of the nonzero elements, as a k×1 index vector (1×k for a 1×n mask); composes with the lt/gt masks and select-rows", "1 + n", "1m(k)", "O(n)", 18 },
	{ "while", "( flag -- )", "Exit the loop forward if flag is falsy (begin … while … repeat)", NULL, NULL, NULL, 8 },
	{ "wildcard?", "( a -- bool )", "core.h2o: type-of :wildcard = (inlined)", "5", "none", "O(1)", 4 },
	{ "with-db", "( path body-xt -- … )", "exceptions.h2o: db-open the path, run body-xt ( db -- … ) with the handle, db-close on either exit", "—", "1 db + cont if thrown", "O(body-xt)", 24 },
	{ "with-intercept", "( X -- X' )", "statistics.h2o: prepend a column of ones, so a fit's beta[0] is the intercept", "r×c", "1m(r×(c+1))", "O(r×c)", 18 },
	{ "with-stream", "( stream body-xt -- … )", "exceptions.h2o: run body-xt ( stream -- … ) over an already-open stream, close it on either exit", "—", "cont if thrown", "O(body-xt)", 24 },
	{ "words", "( -- )", "List all non-internal words in aligned columns, grouped by reference section, alphabetical within a group; session-defined words first", "dict scan", "none", "O(|dict| log |dict|)", 29 },
	{ "write", "( s stream -- )", "Write the string's bytes to the stream; loops over partial writes, retries EINTR", "write syscalls", "none", "O(|s|)", 32 },
	{ "write-file", "( s path -- )", "Create or truncate the file, then write the string's bytes", "file write", "none", "O(|s|)", 31 },
	{ "write-in", "( s proc -- )", "subprocess.h2o: write the string to the child's :in stream", "write syscalls", "none", "O(|s|)", 32 },
	{ "write-tsv", "( rows path -- )", "Write an array of row-arrays as TSV; none → empty, a whole-number float → integer, strings raw; errors on a tab/newline inside a string or a non-array row", "2 + r·c", "none (to file)", "O(r·c)", 22 },
	{ "xml-escape", "( s -- s' )", "strings.h2o: & < > ' to their XML entities, for element text and single-quoted attributes; four replace passes", "4n", "4 strings", "O(n)", 12 },
	{ "xt?", "( a -- bool )", "core.h2o: type-of :xt = (inlined)", "5", "none", "O(1)", 4 },
	{ "yield", "( v -- resumed )", "generators.h2o: shift — emit v to the driver; returns whatever the driver passes back via resume", "L", "1o (cont)", "O(L)", 25 },
	{ "{", "—", "Open a frame literal (alternating key/value); } closes it", NULL, NULL, NULL, 9 },
	{ "|", "—", "Declare word-locals at a definition's head: | x y |", NULL, NULL, NULL, 9 },
	{ "|>", "—", "Locals list in which every slot receives from the stack", NULL, NULL, NULL, 9 },
	{ "}", "—", "Close a frame literal", NULL, NULL, NULL, 9 },
	{ "~", "( a b -- term )", "C primitive alias of unify, so cons ~ fuses to (cons~)", "n", "none", "O(n)", 26 },
};

const int help_entry_count = 491;
