/* Generated by tools/gen-editors.py from the curated highlight groups.
   Shared by the editor syntax files and the REPL highlighter (core.c).
   Do not edit by hand; rerun `make editors`. */

static const char *const lf_control[] = {"if", "?if", "else", "then", "begin", "until", "again", "while", "repeat", "leave", "continue", "times", "i-times", "exit", "execute", NULL};
static const char *const lf_defining[] = {":", ";", "variable", "constant", "symbol", "to", "forget", "inline", "internal", "'", "lookup", NULL};
static const char *const lf_logicwords[] = {"lvar", "unify", "~", "deref", "$", "amb", "fail", "_", NULL};
