#!/usr/bin/env python3
"""Generate the editor syntax files from docs/reference.md.

Maintainer tool: run when reference.md changes (alongside gen-help.py). The
generated files are committed, so editors need no build step.

Source of truth: the word-tables in reference.md (a row whose first cell is a
single bare-backtick token is a word). That set is exactly the public surface
— internal `(branch)`-style compiler words never appear there.

Categorization: a small curated map fixes the stable structural groups
(defining / control / logic / boolean / operators); every other public word is
auto-routed to "builtins". New words therefore highlight automatically. The
bracket/quotation delimiters ([ ] { } < > | [: :] [( )]) are matched by regex
rules in the templates, not keyword lists, so they are excluded here.

Emits:
  editors/vim/syntax/logicforth.vim
  editors/vscode/syntaxes/logicforth.tmLanguage.json
"""

import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REFERENCE = os.path.join(ROOT, "docs", "reference.md")
VIM_OUT = os.path.join(ROOT, "editors", "vim", "syntax", "logicforth.vim")
VSCODE_OUT = os.path.join(ROOT, "editors", "vscode", "syntaxes", "logicforth.tmLanguage.json")

ROW_SPLIT = re.compile(r"(?<!\\)\|")
WORD_CELL = re.compile(r"^`([^`\s]+)`$")

# --- Curated structural groups (stable; everything else is a builtin) --------
DEFINING = [":", ";", "variable", "symbol", "to", "forget", "inline", "'", "lookup", "immediate"]
CONDITIONAL = ["if", "?if", "else", "then"]
REPEAT = ["begin", "until", "again", "while", "repeat", "times", "i-times"]
KEYWORD = ["exit", "execute"]
LOGIC = ["lvar", "unify", "~", "deref", "$", "amb", "fail", "_"]
BOOLEAN = ["null"]
OPERATORS = [
    "|>", "+!", "-!", "*!", "/!", "++", "--", "f++", "f--", "f1+", "f1-",
    "f+", "f-", "f*", "f/", "f^", "1+", "1-", "0=", "+", "-", "*", "/", "%",
    "^", "=", "!i", "!", "@i,j", "@i", "@j", "@", ">r", ">side", "side>",
    "2dup", ".s", ".a", ".",
]
# Handled by regex match rules in the templates, never a keyword.
DELIMITERS = {"[", "]", "{", "}", "<", ">", "|", "[:", ":]", "[(", ")]"}
# Documentation pseudo-words (symbol-literal examples), matched by the symbol scope.
EXCLUDE = {":name"}

CURATED = DEFINING + CONDITIONAL + REPEAT + KEYWORD + LOGIC + BOOLEAN + OPERATORS


def reference_words():
    with open(REFERENCE, encoding="utf-8") as handle:
        lines = handle.read().splitlines()
    words, seen = [], set()
    i = 0
    while i < len(lines):
        if not lines[i].lstrip().startswith("|"):
            i += 1
            continue
        header = ROW_SPLIT.split(lines[i].strip())
        sep = i + 1 < len(lines) and all(
            re.fullmatch(r"\s*:?-{2,}:?\s*", p) for p in ROW_SPLIT.split(lines[i + 1]) if p.strip() != ""
        )
        is_word_table = len(header) >= 2 and header[1].strip() == "Word"
        if not sep:
            i += 1
            continue
        i += 2
        while i < len(lines) and lines[i].lstrip().startswith("|"):
            cells = [c for c in ROW_SPLIT.split(lines[i].strip())]
            cells = [c for c in cells if c != ""] if cells else cells
            i += 1
            if not is_word_table or not cells:
                continue
            m = WORD_CELL.match(cells[0].strip())
            if not m:
                continue
            name = m.group(1)
            if name not in seen:
                seen.add(name)
                words.append(name)
    return words


def builtins(words):
    special = set(CURATED) | DELIMITERS | EXCLUDE
    return sorted(w for w in words if w not in special)


def wrap(words, width=12):
    return [words[i:i + width] for i in range(0, len(words), width)]


def emit_vim(auto):
    L = []
    L.append('" Vim syntax file for logicforth (.l4)')
    L.append('" GENERATED by tools/gen-editors.py from docs/reference.md — do not edit by hand.')
    L.append('" Relies on the broad \'iskeyword\' set below so punctuation words (+, ~, >r,')
    L.append('" @i,j, has?, kebab-case) match as keywords.')
    L.append("")
    L.append('if exists("b:current_syntax")')
    L.append("  finish")
    L.append("endif")
    L.append("")
    L.append("syn case match")
    L.append("syn iskeyword @,48-57,_,192-255,33,35-39,42-47,58-64,94,126")
    L.append("")
    L.append("syn match   logicforthComment \"\\%(^\\|\\s\\)\\zs\\\\\\%(\\s.*\\)\\=$\" contains=@Spell")
    L.append('syn region  logicforthComment start="\\[\\@<!(\\s" end=")" contains=@Spell')
    L.append('syn region  logicforthString start=+"+ skip=+""+ end=+"+ contains=@Spell')
    L.append('syn match   logicforthNumber "\\<-\\=\\d\\+\\%(\\.\\d\\+\\)\\=\\%([eE][-+]\\=\\d\\+\\)\\=\\>"')
    L.append('syn match   logicforthSymbol  ":\\k\\+"')
    L.append('syn match   logicforthPath    "/\\a\\k*"')
    L.append('syn match   logicforthLogicVar "\\<\\u\\w*\\>"')
    L.append("")

    def kw(group, items):
        return "syn keyword %s %s" % (group, " ".join(items))

    L.append(kw("logicforthDefine", DEFINING))
    L.append('syn match   logicforthDefine "\\[:"')
    L.append('syn match   logicforthDefine ":\\]"')
    L.append('syn match   logicforthDefName "\\%(^\\|\\s\\):\\s\\+\\zs\\k\\+"')
    L.append("")
    L.append(kw("logicforthConditional", CONDITIONAL))
    L.append(kw("logicforthRepeat", REPEAT))
    L.append(kw("logicforthKeyword", KEYWORD))
    L.append("")
    L.append(kw("logicforthLogic", LOGIC))
    L.append(kw("logicforthBoolean", BOOLEAN))
    L.append("")
    L.append('syn match   logicforthDelimiter "[][{}<>]"')
    L.append('syn match   logicforthDelimiter "\\[("')
    L.append('syn match   logicforthDelimiter ")\\]"')
    L.append('syn match   logicforthDelimiter "\\s\\zs|\\ze\\s"')
    L.append("")
    # vim folds operators into the builtin group (the broad iskeyword covers them).
    for chunk in wrap(OPERATORS + auto):
        L.append(kw("logicforthBuiltin", chunk))
    L.append("")
    for grp, link in [
        ("Comment", "Comment"), ("String", "String"), ("Number", "Number"),
        ("Symbol", "Constant"), ("Path", "Constant"), ("LogicVar", "Identifier"),
        ("Define", "Define"), ("DefName", "Function"), ("Conditional", "Conditional"),
        ("Repeat", "Repeat"), ("Keyword", "Keyword"), ("Logic", "Special"),
        ("Boolean", "Boolean"), ("Delimiter", "Delimiter"), ("Builtin", "Statement"),
    ]:
        L.append("hi def link logicforth%-12s %s" % (grp, link))
    L.append("")
    L.append('let b:current_syntax = "logicforth"')
    L.append("")
    return "\n".join(L)


_META = set(r"\^$.|?*+()[]{}")


def esc(word):
    return "".join("\\" + c if c in _META else c for c in word)


def alt(words):
    # Whole-token anchored alternation; order-independent thanks to the anchors.
    body = "|".join(esc(w) for w in words)
    return r"(?<=^|\s)(?:%s)(?=\s|$)" % body


def emit_vscode(auto):
    grammar = {
        "$schema": "https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json",
        "name": "logicforth",
        "scopeName": "source.logicforth",
        "_generated": "by tools/gen-editors.py from docs/reference.md — do not edit by hand",
        "patterns": [{"include": "#" + n} for n in [
            "comments", "strings", "numbers", "quotation", "control", "defining",
            "logic", "constants", "operators", "builtins", "symbol", "path",
            "logicvar", "delimiters",
        ]],
        "repository": {
            "comments": {"patterns": [
                {"name": "comment.line.backslash.logicforth", "match": r"(?<=^|\s)\\(?:\s.*)?$"},
                {"name": "comment.block.logicforth", "begin": r"(?<=^|\s)\(\s", "end": r"\)"},
            ]},
            "strings": {
                "name": "string.quoted.double.logicforth", "begin": "\"", "end": "\"(?!\")",
                "patterns": [{"name": "constant.character.escape.logicforth", "match": "\"\""}],
            },
            "numbers": {"name": "constant.numeric.logicforth",
                        "match": r"(?<=^|\s)-?\d+(?:\.\d+)?(?:[eE][-+]?\d+)?(?=\s|$)"},
            "quotation": {"name": "keyword.declaration.logicforth",
                          "match": r"(?<=^|\s)(?:\[:|:\])(?=\s|$)"},
            "control": {"name": "keyword.control.logicforth", "match": alt(CONDITIONAL + REPEAT + KEYWORD)},
            "defining": {"name": "keyword.declaration.logicforth", "match": alt(DEFINING)},
            "logic": {"name": "keyword.other.logic.logicforth", "match": alt(LOGIC)},
            "constants": {"name": "constant.language.logicforth", "match": alt(BOOLEAN)},
            "operators": {"name": "keyword.operator.logicforth", "match": alt(OPERATORS)},
            "builtins": {"name": "support.function.logicforth", "match": alt(auto)},
            "symbol": {"name": "constant.other.symbol.logicforth", "match": r"(?<=^|\s):\S+"},
            "path": {"name": "constant.other.path.logicforth", "match": r"(?<=^|\s)/[A-Za-z]\S*"},
            "logicvar": {"name": "variable.other.logicvar.logicforth",
                         "match": r"(?<=^|\s)[A-Z][A-Za-z0-9_]*(?=\s|$)"},
            "delimiters": {"name": "punctuation.section.logicforth", "match": r"\[\(|\)\]|[\[\]{}<>]"},
        },
    }
    return json.dumps(grammar, indent=2) + "\n"


def main():
    words = reference_words()
    auto = builtins(words)
    with open(VIM_OUT, "w", encoding="utf-8") as handle:
        handle.write(emit_vim(auto))
    with open(VSCODE_OUT, "w", encoding="utf-8") as handle:
        handle.write(emit_vscode(auto))
    print("%d reference words; %d builtins; wrote %s and %s"
          % (len(words), len(auto), VIM_OUT, VSCODE_OUT))


if __name__ == "__main__":
    main()
