#!/usr/bin/env python3
"""Generate the editor syntax files from docs/reference.md.

Maintainer tool: run when reference.md changes (alongside gen-help.py). The
generated files are committed, so editors need no build step.

Source of truth: the word-tables in reference.md (a row whose first cell is a
single bare-backtick token is a word). That set is exactly the public surface
— internal `(branch)`-style compiler words never appear there.

Categorization: a small curated map fixes the stable structural groups
(defining / control / logic / boolean / operators); every other public word is
auto-routed to "builtins". New words therefore highlight automatically. The
bracket/quotation delimiters ([ ] { } < > | [: :] [( )]) are matched by regex
rules in the templates, not keyword lists, so they are excluded here.

Emits:
  editors/vim/syntax/water.vim
  editors/vscode/syntaxes/water.tmLanguage.json
"""

import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REFERENCE = os.path.join(ROOT, "docs", "reference.md")
VIM_OUT = os.path.join(ROOT, "editors", "vim", "syntax", "water.vim")
VSCODE_OUT = os.path.join(ROOT, "editors", "vscode", "syntaxes", "water.tmLanguage.json")
HEADER_OUT = os.path.join(ROOT, "src", "c", "repl_highlight_groups.h")

ROW_SPLIT = re.compile(r"(?<!\\)\|")
WORD_CELL = re.compile(r"^`([^`\s]+)`$")

# --- Curated structural groups (stable; everything else is a builtin) --------
DEFINING = [":", ";", "variable", "constant", "symbol", "to", "forget", "inline", "internal", "'", "lookup"]
CONDITIONAL = ["if", "?if", "else", "then"]
REPEAT = ["begin", "until", "again", "while", "repeat", "leave", "continue", "times", "i-times"]
KEYWORD = ["exit", "execute"]
LOGIC = ["lvar", "unify", "~", "deref", "$", "amb", "fail", "_"]
BOOLEAN = ["null"]
OPERATORS = [
    "|>", "+!", "-!", "*!", "/!", "++", "--", "f++", "f--", "f1+", "f1-",
    "f+", "f-", "f*", "f/", "f^", "1+", "1-", "0=", "+", "-", "*", "/", "%",
    "^", "=", "!i", "!", "@i,j", "@i", "@j", "@", ">r", ">side", "side>",
    "2dup", ".s", ".a", ".",
]
# Handled by regex match rules in the templates, never a keyword.
DELIMITERS = {"[", "]", "{", "}", "<", ">", "|", "[:", ":]", "[(", ")]", "[|", "[>"}
# Documentation pseudo-words (symbol-literal examples), matched by the symbol scope.
EXCLUDE = {":name"}

CURATED = DEFINING + CONDITIONAL + REPEAT + KEYWORD + LOGIC + BOOLEAN + OPERATORS


def reference_words():
    with open(REFERENCE, encoding="utf-8") as handle:
        lines = handle.read().splitlines()
    words, seen = [], set()
    i = 0
    while i < len(lines):
        if not lines[i].lstrip().startswith("|"):
            i += 1
            continue
        header = ROW_SPLIT.split(lines[i].strip())
        sep = i + 1 < len(lines) and all(
            re.fullmatch(r"\s*:?-{2,}:?\s*", p) for p in ROW_SPLIT.split(lines[i + 1]) if p.strip() != ""
        )
        is_word_table = len(header) >= 2 and header[1].strip() == "Word"
        if not sep:
            i += 1
            continue
        i += 2
        while i < len(lines) and lines[i].lstrip().startswith("|"):
            cells = [c for c in ROW_SPLIT.split(lines[i].strip())]
            cells = [c for c in cells if c != ""] if cells else cells
            i += 1
            if not is_word_table or not cells:
                continue
            m = WORD_CELL.match(cells[0].strip())
            if not m:
                continue
            name = m.group(1).replace("\\|", "|")
            if name not in seen:
                seen.add(name)
                words.append(name)
    return words


def builtins(words):
    special = set(CURATED) | DELIMITERS | EXCLUDE
    return sorted(w for w in words if w not in special)


def wrap(words, width=12):
    return [words[i:i + width] for i in range(0, len(words), width)]


def emit_vim(auto):
    L = []
    L.append('" Vim syntax file for water (.h2o)')
    L.append('" GENERATED by tools/gen-editors.py from docs/reference.md — do not edit by hand.')
    L.append('" Relies on the broad \'iskeyword\' set below so punctuation words (+, ~, >r,')
    L.append('" @i,j, has?, kebab-case) match as keywords.')
    L.append("")
    L.append('if exists("b:current_syntax")')
    L.append("  finish")
    L.append("endif")
    L.append("")
    L.append("syn case match")
    L.append("syn iskeyword @,48-57,_,192-255,33,35-39,42-47,58,60-64,94,126")
    L.append("")
    L.append("syn match   waterComment \"\\%(^\\|\\s\\)\\zs\\\\\\%(\\s.*\\)\\=$\" contains=@Spell")
    L.append('syn region  waterComment start="\\[\\@<!(\\s" end=")" contains=@Spell')
    L.append('syn region  waterString start=+"+ skip=+""+ end=+"+ contains=@Spell,waterFormat')
    L.append('syn match   waterFormat "{\\d\\+\\%(:[^}]*\\)\\=}" contained')
    L.append('syn match   waterNumber "\\<-\\=\\d\\+\\%(\\.\\d\\+\\)\\=\\%([eE][-+]\\=\\d\\+\\)\\=\\>"')
    L.append('syn match   waterSymbol  ":\\k\\+"')
    L.append('syn match   waterPath    "/\\a\\k*"')
    L.append('syn match   waterLogicVar "\\<\\u\\k*\\>"')
    L.append("")

    def kw(group, items):
        return "syn keyword %s %s" % (group, " ".join(items))

    L.append(kw("waterDefine", [w for w in DEFINING if w != ";"]))
    L.append('syn match   waterDefine ";"')
    L.append('syn match   waterDefine "\\[:"')
    L.append('syn match   waterDefine "\\[|"')
    L.append('syn match   waterDefine "\\[>"')
    L.append('syn match   waterDefine ":\\]"')
    L.append('syn match   waterDefName "\\%(^\\|\\s\\):\\s\\+\\zs\\k\\+"')
    L.append("")
    L.append(kw("waterConditional", CONDITIONAL))
    L.append(kw("waterRepeat", REPEAT))
    L.append(kw("waterKeyword", KEYWORD))
    L.append("")
    L.append(kw("waterLogic", LOGIC))
    L.append(kw("waterBoolean", BOOLEAN))
    L.append("")
    L.append('syn match   waterDelimiter "[][{}<>]"')
    L.append('syn match   waterDelimiter "\\[("')
    L.append('syn match   waterDelimiter ")\\]"')
    L.append('syn match   waterDelimiter "\\s\\zs|\\ze\\s"')
    L.append("")
    # vim folds operators into the builtin group (the broad iskeyword covers them).
    # `|` is a vim command separator and `"` starts a comment, so tokens containing
    # them can't go in `syn keyword` (E488) — emit those via `syn match` instead.
    kw_tokens = [t for t in OPERATORS + auto if "|" not in t and '"' not in t]
    match_tokens = [t for t in OPERATORS + auto if "|" in t or '"' in t]
    for chunk in wrap(kw_tokens):
        L.append(kw("waterBuiltin", chunk))
    for tok in match_tokens:
        escaped = "".join("\\" + c if c in "\\.*[]^$~/" else c for c in tok)
        L.append('syn match   waterBuiltin "%s"' % escaped)
    L.append("")
    for grp, link in [
        ("Comment", "Comment"), ("String", "String"), ("Number", "Number"),
        ("Symbol", "Constant"), ("Path", "Constant"), ("LogicVar", "Identifier"),
        ("Define", "Define"), ("DefName", "Function"), ("Conditional", "Conditional"),
        ("Repeat", "Repeat"), ("Keyword", "Keyword"), ("Logic", "Special"),
        ("Boolean", "Boolean"), ("Delimiter", "Delimiter"), ("Builtin", "Statement"),
        ("Format", "SpecialChar"),
    ]:
        L.append("hi def link water%-12s %s" % (grp, link))
    L.append("")
    L.append('let b:current_syntax = "water"')
    L.append("")
    return "\n".join(L)


_META = set(r"\^$.|?*+()[]{}")


def esc(word):
    return "".join("\\" + c if c in _META else c for c in word)


# Self-delimiting punctuation: ; ] } always end a token, [ { always start one,
# and :] / )] are two-char closers — so token boundaries are whitespace OR
# these characters, mirroring next_token in core.c.
BOUNDARY_BEHIND = r"(?<=^|\s|[\[\]{};])"
BOUNDARY_AHEAD = r"(?=$|\s|[\[\]{};]|:\]|\)\])"


def alt(words):
    # Whole-token anchored alternation; order-independent thanks to the anchors.
    body = "|".join(esc(w) for w in words)
    return r"%s(?:%s)%s" % (BOUNDARY_BEHIND, body, BOUNDARY_AHEAD)


def emit_vscode(auto):
    grammar = {
        "$schema": "https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json",
        "name": "water",
        "scopeName": "source.water",
        "_generated": "by tools/gen-editors.py from docs/reference.md — do not edit by hand",
        "patterns": [{"include": "#" + n} for n in [
            "comments", "strings", "numbers", "quotation", "control", "defining",
            "logic", "constants", "operators", "builtins", "symbol", "path",
            "logicvar", "delimiters",
        ]],
        "repository": {
            "comments": {"patterns": [
                {"name": "comment.line.backslash.water", "match": r"(?<=^|\s)\\(?:\s.*)?$"},
                {"name": "comment.block.water", "begin": r"(?<=^|\s)\(\s", "end": r"\)"},
            ]},
            "strings": {
                "name": "string.quoted.double.water", "begin": "\"", "end": "\"(?!\")",
                "patterns": [
                    {"name": "constant.character.escape.water", "match": "\"\""},
                    {"name": "constant.other.placeholder.water", "match": r"\{\d+(?::[^}]*)?\}"},
                ],
            },
            "numbers": {"name": "constant.numeric.water",
                        "match": BOUNDARY_BEHIND + r"-?\d+(?:\.\d+)?(?:[eE][-+]?\d+)?" + BOUNDARY_AHEAD},
            "quotation": {"name": "keyword.declaration.water",
                          "match": r"\[:|\[\||\[>|:\]"},
            "control": {"name": "keyword.control.water", "match": alt(CONDITIONAL + REPEAT + KEYWORD)},
            "defining": {"name": "keyword.declaration.water", "match": alt(DEFINING)},
            "logic": {"name": "keyword.other.logic.water", "match": alt(LOGIC)},
            "constants": {"name": "constant.language.water", "match": alt(BOOLEAN)},
            "operators": {"name": "keyword.operator.water", "match": alt(OPERATORS)},
            "builtins": {"name": "support.function.water", "match": alt(auto)},
            "symbol": {"name": "constant.other.symbol.water",
                       "match": BOUNDARY_BEHIND + r":[^\s\[\]{};]+"},
            "path": {"name": "constant.other.path.water",
                     "match": BOUNDARY_BEHIND + r"/[A-Za-z][^\s{};]*"},
            "logicvar": {"name": "variable.other.logicvar.water",
                         "match": BOUNDARY_BEHIND + r"[A-Z][^\s\[\]{};]*" + BOUNDARY_AHEAD},
            "delimiters": {"name": "punctuation.section.water", "match": r"\[\(|\)\]|[\[\]{}<>]"},
        },
    }
    return json.dumps(grammar, indent=2) + "\n"


def c_array(name, words):
    items = ", ".join('"' + w.replace("\\", "\\\\").replace('"', '\\"') + '"' for w in words)
    return "static const char *const %s[] = {%s, NULL};" % (name, items)


def emit_c_header():
    return "\n".join([
        "/* Generated by tools/gen-editors.py from the curated highlight groups.",
        "   Shared by the editor syntax files and the REPL highlighter (core.c).",
        "   Do not edit by hand; rerun `make editors`. */",
        "",
        c_array("lf_control", CONDITIONAL + REPEAT + KEYWORD),
        c_array("lf_defining", DEFINING),
        c_array("lf_logicwords", LOGIC),
        "",
    ])


def main():
    words = reference_words()
    auto = builtins(words)
    with open(VIM_OUT, "w", encoding="utf-8") as handle:
        handle.write(emit_vim(auto))
    with open(VSCODE_OUT, "w", encoding="utf-8") as handle:
        handle.write(emit_vscode(auto))
    with open(HEADER_OUT, "w", encoding="utf-8") as handle:
        handle.write(emit_c_header())
    print("%d reference words; %d builtins; wrote %s, %s, %s"
          % (len(words), len(auto), VIM_OUT, VSCODE_OUT, HEADER_OUT))


if __name__ == "__main__":
    main()
